### ISSUE TITLE
Ensure that we have a way to check a client's IP addresses

### ISSUE THREAD

**Issue by tiago-loureiro** [wireapp/wire-server-deploy#119]
On our cloud solution we use some ELB's specifics, we need to revise this wrt on prem installations, when ELB's or other load balancers are there. We should be able to see a client's IP address at the _ingress/nginz/backend services_ level, either for rate limiting or logging purposes.

Something relevant from the nginx-ingress for instance: https://github.com/helm/charts/tree/master/stable/nginx-ingress

| Parameter | Description | Default value |
| ------------- | ------------- | -------- |
| controller.service.externalTrafficPolicy | If controller.service.type is NodePort or LoadBalancer, set this to Local to enable source IP preservation | "Cluster" |

**Comment by arianvp** [comment]
When we set `externalTrafficPolicy:  Local`  then unfortunately requests will only succeed if you send a request specifically to the `node` on which the `pod` is running. 
Without `local` then if we hit a node that does not run the pod, `kube-proxy` will redirect it to the correct one automagically. 

So if we want to use this,  we need to make sure to assign the ingress controller to a known set of nodes. 

From https://kubernetes.github.io/ingress-nginx/deploy/baremetal/
> This setting effectively drops packets sent to Kubernetes nodes which are not running any instance of the NGINX Ingress controller. Consider assigning NGINX Pods to specific nodes in order to control on what nodes the NGINX Ingress controller should be scheduled or not scheduled.

More info on how to do that here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/

We could just run the ingress controller as a `DaemonSet`. This would make it run on each node in the cluster; solving the problem.    Or we could set up some node affinity / node selector rules to make it schedule on a subset of nodes that we specify.  I honestly think just running it as a `DaemonSet` is the easiest course of action
