### ISSUE TITLE
default Kubespray config claims kubelets will load-balance access to apiserver but it doesn't seem to be the case

### ISSUE THREAD

**Issue by arianvp** [wireapp/wire-server-deploy#138]
From the Documentaiton from Kubespray (emphasis mine)

https://github.com/kubernetes-sigs/kubespray/blob/master/docs/ha-mode.md#kube-apiserver

> K8s components require a loadbalancer to access the apiservers via a reverse proxy. Kubespray includes support for an nginx-based proxy that resides on each **non-master** Kubernetes node. This is referred to as localhost loadbalancing. It is less efficient than a dedicated load balancer because it creates extra health checks on the Kubernetes apiserver, but is more practical for scenarios where an external LB or virtual IP management is inconvenient. This option is configured by the variable loadbalancer_apiserver_localhost (defaults to True. Or False, if there is an external loadbalancer_apiserver defined). You may also define the port the local internal loadbalancer uses by changing, loadbalancer_apiserver_port. This defaults to the value of kube_apiserver_port. It is also important to note that Kubespray will only configure kubelet and kube-proxy on non-master nodes to use the local internal loadbalancer.

So this would mean that there is `nginx` running on each node that runs `kubelet` and that `nginx` will forward the `kubelet` traffic to any of the **three** apiservers.

However, the documentation seems to vaguely suggest this is only installed on **non-master** nodes. Note sure what that means. Are our worker nodes (that are also masters) considered **non-master** nodes by kubespray? We should probably have a look at their playbooks.  It seems the case that for us, our kubelets are not configured by default to talk to the apiserver in a highly available way. I hope this is just a small config change in ansible to kick this thing in the right direction.

On the kubesprayed installation that @julialongtin sprayed today, there is no `nginx` running locally and the `kubelet.conf` seems to be configured to talk _directly_ to the apiserver that is only on the same note as the `kubelet`.    Not on an `nginx` running on port `:443` as documented in their documentation. So this seems to suggest this load balancing component of `kubespray`'s installation procedure was not installed for some reason.

```
root@kubenode01:~# cat /etc/kubernetes/kubelet.conf 
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data:  "<redacted>"
    server: https://10.0.0.39:6443
  name: cluster.local
```

Note that for components that talk to the apiserver _inside_ the cluster `kube-proxy` takes care of the load-balancing and everything is fine. It's just the kubelets that only talk to their local apiserver.

```
root@kubenode01:~# kubectl describe svc kubernetes
Name:              kubernetes
Namespace:         default
Labels:            component=apiserver
                   provider=kubernetes
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP:                10.233.0.1
Port:              https  443/TCP
TargetPort:        6443/TCP
Endpoints:         10.0.0.39:6443,10.0.0.40:6443,10.0.0.41:6443
Session Affinity:  None
Events:            <none>

```

**Comment by arianvp** [comment]
# What I observed when configuring our dev cluster

![Current infra](https://user-images.githubusercontent.com/628387/63785056-000bf280-c8f0-11e9-858e-5d01e6f99fa6.png)

# What kubespray documents that should happen
(Assuming they do no weird checks that nginx isnt installed on "master" nodes)
![Wanted Infra](https://user-images.githubusercontent.com/628387/63785097-131ec280-c8f0-11e9-9d5c-6cf99e84a46b.png)

**Comment by jschaul** [comment]
There are worker nodes, and there are master nodes. In the setup from ansible, by default:

```
[kube-master]
node0
node1
node2

[kube-node]
node0
node1
node2
```

each virtual machine is both a worker and a master. So there are no non-master nodes in your cluster. Just add a VM, and add it to the [kube-node] group (but not to the kube-master group!), and re-run the playbook. You should probably then see the documented behaviour and can close this issue.

**Comment by arianvp** [comment]
Will do!

I also am now convinced that it makes sense to directly access the apiserver on a `master` node that is also a `worker`) because yeh.... the apiserver is actually there locally in the first place :)

**Comment by arianvp** [comment]
I'm going to close this for now. and will check later whether this works as expected when setting up extra worker nodes in my test cluster. Thanks for the pointer @jschaul

**Comment by arianvp** [comment]
https://github.com/kubernetes-sigs/kubespray/blob/0cc5e3ef0331ac2d9d89adb337c4e62f6688eeae/roles/kubernetes/node/tasks/main.yml#L20-L26

We only run master-nodes on-prem. Because each master node always runs a copy of apiserver; there is never a case where a kubelet can't talk to the apiserver. Hence a loadbalancer is not needed.

Hope this helps for any bystander who is confused by this =)
