### ISSUE TITLE
Unable to deploy wire server on the kubernetes due to cassandra-migration pod failing

### ISSUE THREAD

**Issue by ramesh8830** [wireapp/wire-server-deploy#163]
Hi,

I am trying deploy wire server demo on the kubernetes cluster but cassandra-migration pod failing due to gundeck-schema. Please check the below details and help me sort this.

Name:               cassandra-migrations-r752j
Namespace:          demo
Priority:           0
PriorityClassName:  <none>
Node:               node1/IP
Start Time:         Mon, 14 Oct 2019 07:38:13 +0000
Labels:             controller-uid=93baf997-ee55-11e9-859d-38d547b2cf63
                    job-name=cassandra-migrations
                    release=wire-server
                    wireService=cassandra-migrations
Annotations:        <none>
Status:             Pending
IP:                 10.233.67.70
Controlled By:      Job/cassandra-migrations
Init Containers:
  gundeck-schema:
    Container ID:  docker://9b4906e2881d69d345b629eb0fda78453b7efdd51df8fc241384416f99fc9921
    Image:         quay.io/wire/gundeck-schema:2.63.0
    Image ID:      docker-pullable://quay.io/wire/gundeck-schema@sha256:ebb21d55f0ef6efb58d9f73505cfdc57195115cf6e745c80e52e694143c994e9
    Port:          <none>
    Host Port:     <none>
    Command:
      gundeck-schema
      --host
      cassandra-ephemeral
      --port
      9042
      --keyspace
      gundeck
      --replication-factor
      3
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 14 Oct 2019 07:38:26 +0000
      Finished:     Mon, 14 Oct 2019 07:38:31 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 14 Oct 2019 07:38:19 +0000
      Finished:     Mon, 14 Oct 2019 07:38:24 +0000
    Ready:          False
    Restart Count:  1
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-svgmk (ro)
  brig-schema:
    Container ID:
    Image:         quay.io/wire/brig-schema:2.63.0
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      brig-schema
      --host
      cassandra-ephemeral
      --port
      9042
      --keyspace
      brig
      --replication-factor
      3
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-svgmk (ro)
  galley-schema:
    Container ID:
    Image:         quay.io/wire/galley-schema:2.63.0
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      galley-schema
      --host
      cassandra-ephemeral
      --port
      9042
      --keyspace
      galley
      --replication-factor
      3
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-svgmk (ro)
  spar-schema:
    Container ID:
    Image:         quay.io/wire/spar-schema:2.63.0
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      spar-schema
      --host
      cassandra-ephemeral
      --port
      9042
      --keyspace
      spar
      --replication-factor
      3
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-svgmk (ro)
Containers:
  job-done:
    Container ID:
    Image:         busybox
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      echo "gundeck, brig, galley, spar schema cassandra-migrations completed. See initContainers for details with e.g. kubectl logs ... -c gundeck-schema"
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-svgmk (ro)
Conditions:
  Type              Status
  Initialized       False
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  default-token-svgmk:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-svgmk
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  23s                default-scheduler  Successfully assigned demo/cassandra-migrations-r752j to node1
  Normal   Pulling    21s                kubelet, node1  Pulling image "quay.io/wire/gundeck-schema:2.63.0"
  Normal   Pulled     17s                kubelet, node1  Successfully pulled image "quay.io/wire/gundeck-schema:2.63.0"
  Normal   Created    10s (x2 over 16s)  kubelet, node1  Created container gundeck-schema
  Normal   Pulled     10s                kubelet, node1  Container image "quay.io/wire/gundeck-schema:2.63.0" already present on machine
  Normal   Started    9s (x2 over 16s)   kubelet, node1  Started container gundeck-schema
  Warning  BackOff    4s                 kubelet, node1  Back-off restarting failed container

**Comment by tiago-loureiro** [comment]
Hi @ramesh8830 

As mentioned on the log, please check (and post here if necessary):
```
kubectl logs -n <namespace> -c gundeck-schema (or other service schemas)
```

**Comment by tiago-loureiro** [comment]
Seems like you don't have a service named `cassandra-ephemeral`. Make sure that the respective helm chart is installed and that the service is accessible.

**Comment by ramesh8830** [comment]
`NAME                                       READY   STATUS                  RESTARTS   AGE
cassandra-ephemeral-0                      1/1     Running                 0          6h19m
cassandra-migrations-r752j                 0/1     Init:CrashLoopBackOff   74         6h2m
demo-smtp-84b7b85ff6-p9nrz                 1/1     Running                 0          6h3m
elasticsearch-ephemeral-57944b969c-rwdcx   1/1     Running                 0          6h19m
fake-aws-dynamodb-5757d74b76-th79m         2/2     Running                 0          6h10m
fake-aws-s3-65b49bbd84-qc8rw               1/1     Running                 0          6h10m
fake-aws-s3-reaper-74945cddf9-6kr9j        1/1     Running                 0          6h10m
fake-aws-sns-5c56774d95-sj6hc              2/2     Running                 0          6h10m
fake-aws-sqs-6d849ddf57-9jrsm              2/2     Running                 0          6h10m
redis-ephemeral-69bb4885bb-w4v5n           1/1     Running                 0          6h19m
`

**Comment by ramesh8830** [comment]
cassandra-ephemeral pod is running without any issue

**Comment by jschaul** [comment]
You've misconfigured things. You're using production (i.e. High-availability mode with at least 3 cassandras needed) configuration (you're using `--replication-factor 3`) but try to apply that to a single cassandra, which will not work, as it cannot replicate data 3 times if there is only one cassandra. 

Please see [how to install a demo wire-server on kubernetes](https://docs.wire.com/how-to/install/helm.html), i.e. make use of [demo-values.yaml](https://raw.githubusercontent.com/wireapp/wire-server-deploy/master/values/wire-server/demo-values.example.yaml) as a basis for installation.

**Comment by ramesh8830** [comment]
I am using production values.yaml and trying to deploy it on 3 virtual machines.

**Comment by jschaul** [comment]
Please use the demo-values for the time being.

If you want a High-available setup, then you need three cassandra instances. Use `cassandra-external` helm chart, and install the underlying cassandra using [this playbook](https://github.com/wireapp/wire-server-deploy/blob/develop/ansible/cassandra.yml). 

Documentation for production installations are in flux (i.e. not complete) and will be improved in the coming days/weeks.

**Comment by lucendio** [comment]
@ramesh8830 In case your issues has been resolved, please close it. Otherwise, please follow up to continue the conversation. Thank you.
