### ISSUE TITLE
error on helm upgrade

### ISSUE THREAD

**Issue by coderzstas** [wireapp/wire-server-deploy#164]
Dear devs ) im getting this errors when trying to do
>  helm upgrade --install databases-ephemeral wire/databases-ephemeral --wait

`UPGRADE FAILED
ROLLING BACK
Error: "databases-ephemeral" has no deployed releases`

same with
> helm upgrade --install fake-aws wire/fake-aws --wait

`UPGRADE FAILED
ROLLING BACK
Error: "fake-aws" has no deployed releases
Error: UPGRADE FAILED: "fake-aws" has no deployed releases`

some debug info 

> helm upgrade --install fake-aws wire/fake-aws --wait --timeout 600 --debug
> [debug] Created tunnel using local port: '33003'
> 
> [debug] SERVER: "127.0.0.1:33003"
> 
> [debug] Fetched wire/fake-aws to /root/.helm/cache/archive/fake-aws-0.74.0.tgz
> 
> UPGRADE FAILED
> ROLLING BACK

Thanks

**Comment by jschaul** [comment]
Have a look at https://docs.wire.com/how-to/install/helm.html#helm-install-upgrade-failed

Possibly your cluster doesn't have sufficient CPU/memory (you can find out by looking at the logs/describe commands)

**Comment by tofutim** [comment]
@coderzstas I'm running into this same issue. Was it the CPU for you? I have allocated 5 cpus and 10 GB of memory to the Ubuntu box, but getting this error. Looks like it installed at least 3 components.
```
bash-4.4# kubectl get pods --all-namespaces
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
default       cassandra-ephemeral-0                      1/1     Running   1          70m
default       elasticsearch-ephemeral-8545b66bcc-k6n5t   1/1     Running   1          70m
default       redis-ephemeral-69bb4885bb-8xf9t           1/1     Running   1          70m
kube-system   coredns-56bc6b976d-fctq2                   1/1     Running   2          6h48m
kube-system   coredns-56bc6b976d-sdwdj                   0/1     Pending   0          6h48m
kube-system   dns-autoscaler-56c969bdb8-w69j2            1/1     Running   2          6h48m
kube-system   kube-apiserver-kubenode01                  1/1     Running   2          6h49m
kube-system   kube-controller-manager-kubenode01         1/1     Running   2          6h49m
kube-system   kube-flannel-l29sr                         2/2     Running   6          6h48m
kube-system   kube-proxy-488kz                           1/1     Running   2          6h48m
kube-system   kube-scheduler-kubenode01                  1/1     Running   2          6h49m
kube-system   kubernetes-dashboard-6c7466966c-v7nd6      1/1     Running   2          6h48m
kube-system   nodelocaldns-lw86z                         1/1     Running   2          6h48m
kube-system   tiller-deploy-c48485567-jgphl              1/1     Running   1          6h41m

```

**Comment by lucendio** [comment]
Each workload ([Concepts > Workloads](https://kubernetes.io/docs/concepts/workloads/pods/pod-overview/)) defined in a chart, may also define resource definitions. [Here](https://github.com/wireapp/wire-server-deploy/blob/develop/charts/cassandra-ephemeral/values.yaml#L8), these configurations are passed down to the actual Cassandra chart. [All our charts](https://github.com/wireapp/wire-server-deploy/tree/develop/charts) are no exception to this Kubernetes-native concept.

For the demo setup, we suggest [1] (under *What you need:*)

> One single virtual machine running ubuntu 16.04 or 18.04 with at least 20 GB of disk, 8 GB of memory, and 8 CPU cores.

[1] https://docs.wire.com/how-to/install/planning.html#demo-installation-trying-functionality-out

**Comment by tofutim** [comment]
I'm leaving this as a crumb in case anyone else runs into the issue. I pumped up the cpu and memory count high but still had the same problems. Ultimately I was able to make progress by deleting databases-ephemeral and reinstalling:
```
helm delete --purge databases-ephemeral
helm upgrade --install databases-ephemeral wire/databases-ephemeral --wait
```
then no problems.
