### ISSUE TITLE
Can't install wire-server demo through helm

### ISSUE THREAD

**Issue by kernelpanic700** [wireapp/wire-server-deploy#167]
I followed installation on https://docs.wire.com/how-to/install/helm.html#helm and after run:
helm upgrade --install wire-server wire/wire-server -f values.yaml -f secrets.yaml --wait
I get error: 
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec): unknown field "podManagementPolicy" in io.k8s.api.core.v1.PodSpec
AFAIK from https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#pod-management-policies 
podManagementPolicy field supported by Kubernetes 1.7 and later, I have version 1.14.2. 
What can be reason of this error?

**Comment by arianvp** [comment]
@kernelpanic700 what helm version were you using?

**Comment by lucendio** [comment]
Fixed with https://github.com/wireapp/wire-server-deploy/commit/a1662b763a388ec6025bd7d375b96497ffd000bb
