### ISSUE TITLE
redis VM and etcd VM in production setup

### ISSUE THREAD

**Issue by ramesh8830** [wireapp/wire-server-deploy#176]
Hi,
In the assumptions, mentioned about redis VM but did not mention about etcd VM.

In hosts.ini file nothing mention about redis but for helm external ansible playbook instructions mentioned about redis network interface, how that works? No ansible playbooks given for redis in wire server deploy repo

Documentation bit confusing to understand about redis and etcd VM and its playbooks.

Please help me understand that.

**Comment by jschaul** [comment]
Hi, thanks for opening an issue. Indeed, the documentation around this could be clearer.

The redis playbook/role is planned but work-in-progress (not actively being worked on). In the meantime, as a workaround, you can use the [`redis-ephemeral` helm chart](https://github.com/wireapp/wire-server-deploy/tree/develop/charts/redis-ephemeral), along with the [reaper](https://github.com/wireapp/wire-server-deploy/tree/develop/charts/reaper) helm chart to get self-healing functionality and short (< 1 minute) downtime on pod/machine failure.

The etcd can be run on the same VMs as the kubernetes master/worker VMs, or separately on different VMs. The choice is up to you. Also see this PR: https://github.com/wireapp/wire-server-deploy/pull/171 that introduces separate etcd VMs.

Does that answer your questions?

**Comment by ramesh8830** [comment]
Yes. Thank you for the information. 

I am getting lots of wss url's getting failed with Invalid frame header. webapp is keep flickering with TRYING TO CONNECT. WIRE MAY NOT BE ABLE TO DELIVER MESSAGES.

WebSocketService.ts:113 WebSocket connection to 'wss://xxxxxxxxxxxxx' failed: Invalid frame header

I am not able to resolve this. Please help me resolve this.

**Comment by jschaul** [comment]
What does your configuration look like regarding the webapp? Have a look at [these settings / variables](https://github.com/wireapp/wire-server-deploy/blob/develop/values/wire-server/prod-values.example.yaml#L165-L204) for the webapp, in particular the `CSP_` variables, and make sure those are set to the DNS names you're using, as you'll otherwise have problems.

Further, make sure your TLS certificates are set and valid. You can use for instance

```
DOMAIN=example.com
PORT=443
echo Q | openssl s_client -showcerts -connect $DOMAIN:$PORT 
```
or
```
DOMAIN=example.com
PORT=443
echo Q | openssl s_client -showcerts -connect $DOMAIN:$PORT 2>/dev/null  | openssl x509 -inform pem -noout -text
```
To see the state of your certificates.

**Comment by ramesh8830** [comment]
139828992164288:error:0200206F:system library:connect:Connection refused:../crypto/bio/b_sock2.c:110:
139828992164288:error:2008A067:BIO routines:BIO_connect:connect error:../crypto/bio/b_sock2.c:111:
 I am receiving above errors when try excute your commands on server.

**Comment by ramesh8830** [comment]
> What does your configuration look like regarding the webapp? Have a look at [these settings / variables](https://github.com/wireapp/wire-server-deploy/blob/develop/values/wire-server/prod-values.example.yaml#L165-L204) for the webapp, in particular the `CSP_` variables, and make sure those are set to the DNS names you're using, as you'll otherwise have problems.
> 
> Further, make sure your TLS certificates are set and valid. You can use for instance
> 
> ```
> DOMAIN=example.com
> PORT=443
> echo Q | openssl s_client -showcerts -connect $DOMAIN:$PORT 
> ```
> 
> or
> 
> ```
> DOMAIN=example.com
> PORT=443
> echo Q | openssl s_client -showcerts -connect $DOMAIN:$PORT 2>/dev/null  | openssl x509 -inform pem -noout -text
> ```
> 
> To see the state of your certificates.

Also I have same setup for the CSP_ variables

    CSP_EXTRA_CONNECT_SRC: "https://*.example.com, wss://*.example.com"
    CSP_EXTRA_IMG_SRC: "https://*.example.com"
    CSP_EXTRA_SCRIPT_SRC: "https://*.example.com"
    CSP_EXTRA_DEFAULT_SRC: "https://*.example.com"
    CSP_EXTRA_FONT_SRC: "https://*.example.com"
    CSP_EXTRA_FRAME_SRC: "https://*.example.com"
    CSP_EXTRA_MANIFEST_SRC: "https://*.example.com"
    CSP_EXTRA_OBJECT_SRC: "https://*.example.com"
    CSP_EXTRA_MEDIA_SRC: "https://*.example.com"
    CSP_EXTRA_PREFETCH_SRC: "https://*.example.com"
    CSP_EXTRA_STYLE_SRC: "https://*.example.com"
    CSP_EXTRA_WORKER_SRC: "https://*.example.com"

**Comment by ramesh8830** [comment]
> DOMAIN=example.com
> PORT=443
> echo Q | openssl s_client -showcerts -connect $DOMAIN:$PORT

The certificates are being loaded correctly on all other servers except clustered servers (all VMs) when I execute above commands.

**Comment by ramesh8830** [comment]
There is nothing do with certificates. Certificates are working correctly. I can't get rid below message and wss connection errors in browser console.

Please help me If i missed any configuration.
[wss connection errors.zip](https://github.com/wireapp/wire-server-deploy/files/4214642/wss.connection.errors.zip)

**Comment by jschaul** [comment]
From docs.wire.com:

> two dns names for the so-called “nginz” component of wire-server (the main REST API entry point), these are usually called nginz-https.<domain> (or wire-https.<domain>) and nginz-ssl.<domain> (or wire-ssl.<domain>).

* Can you check you have two DNS names set (one for http traffic, one for websocket traffic)? 
* That the webapp [is configured to use these names](https://github.com/wireapp/wire-server-deploy/blob/develop/values/wire-server/prod-values.example.yaml#L172)? 
* And that the ingress is [also configured to use these hostnames](https://github.com/wireapp/wire-server-deploy/blob/develop/values/nginx-ingress-services/prod-values.example.yaml#L13)?

Further, open your browser "console" and check for any errors there, as well as the "network" tab to check which URL is loaded.

**Comment by ramesh8830** [comment]
**- Can you check you have two DNS names set (one for http traffic, one for websocket traffic)?**
Yes. api.example.com (nginz-https) and wss.example.com (nginz-ssl)
**- That the webapp is configured to use these names?**
Yes. Webapp is configured to use those domain names
**- And that the ingress is also configured to use these hostnames?**
Yes. ingress is also configured to use those domain names

**Chrome Browser Console error:**
WebSocketService.ts:113 WebSocket connection to 'wss://wss.example.com/await?access_token=Mx3k6jHWJCfYEB7o_YDfYlReY1vAwxhm5m7CXtTM2iN24YT3erQJR9vQswTHFol-kMuw6yAQTCmMtIc7MFlJBA==.v=1.k=1.d=1581958996.t=a.l=.u=e0350c07-9924-48dc-b52d-e9566f2e3d04.c=14256953078810558436&client=9a90005d75d6a140' failed: Invalid frame header

**Network:**

Request URL: wss://wss.example.com/await?access_token=Mx3k6jHWJCfYEB7o_YDfYlReY1vAwxhm5m7CXtTM2iN24YT3erQJR9vQswTHFol-kMuw6yAQTCmMtIc7MFlJBA==.v=1.k=1.d=1581958996.t=a.l=.u=e0350c07-9924-48dc-b52d-e9566f2e3d04.c=14256953078810558436&client=9a90005d75d6a140
Request Method: GET
Status Code: 101 WebSocket Protocol Handshake
Access-Control-Allow-Origin: https://app.example.com
Access-Control-Expose-Headers: Request-Id, Location
Connection: upgrade
Date: Mon, 17 Feb 2020 16:52:40 GMT
Request-Id: 3945d9acf19661cb73d34ffc354f2a53
Sec-WebSocket-Accept: UYjDqCoKWC/YsMSyKXKDCJ7j7hQ=
Server: openresty/1.15.8.1
Strict-Transport-Security: max-age=15724800; includeSubDomains
Upgrade: websocket
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,te;q=0.8
Cache-Control: no-cache
Connection: Upgrade
Host: wss.example.com
Origin: https://app.example.com
Pragma: no-cache
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Sec-WebSocket-Key: sNhyUFOzGBYMpCvWggiEwQ==
Sec-WebSocket-Version: 13
Upgrade: websocket
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
access_token: Mx3k6jHWJCfYEB7o_YDfYlReY1vAwxhm5m7CXtTM2iN24YT3erQJR9vQswTHFol-kMuw6yAQTCmMtIc7MFlJBA==.v=1.k=1.d=1581958996.t=a.l=.u=e0350c07-9924-48dc-b52d-e9566f2e3d04.c=14256953078810558436
client: 9a90005d75d6a140

**Comment by jschaul** [comment]
I/we have not come across this problem (`Invalid frame header`) before on the installations we have done, so I'm not sure I can help you further here.

**Comment by ramesh8830** [comment]
```
kubectl -n production logs -f gundeck-544cb6fd7f-49fvs --tail 10
1:E,7:request,1:=,32:e7c5a802695bbc7a74736f8085951670,73:Network.Socket.connect: <socket: 13>: does not exist (Connection refused),
1:E,7:request,1:=,32:e7c5a802695bbc7a74736f8085951670,73:Network.Socket.connect: <socket: 13>: does not exist (Connection refused),
1:E,7:request,1:=,32:1d683089ec624d7b327216baf012f83f,73:Network.Socket.connect: <socket: 13>: does not exist (Connection refused),
1:E,7:request,1:=,32:1d683089ec624d7b327216baf012f83f,73:Network.Socket.connect: <socket: 13>: does not exist (Connection refused),
1:E,7:request,1:=,32:1d683089ec624d7b327216baf012f83f,73:Network.Socket.connect: <socket: 13>: does not exist (Connection refused),
1:E,7:request,1:=,32:1d683089ec624d7b327216baf012f83f,73:Network.Socket.connect: <socket: 13>: does not exist (Connection refused),
1:E,7:request,1:=,32:91331a2848d41956aeeec639663b1162,73:Network.Socket.connect: <socket: 13>: does not exist (Connection refused),
1:E,7:request,1:=,32:91331a2848d41956aeeec639663b1162,73:Network.Socket.connect: <socket: 13>: does not exist (Connection refused),
1:E,7:request,1:=,32:91331a2848d41956aeeec639663b1162,73:Network.Socket.connect: <socket: 26>: does not exist (Connection refused),
1:E,7:request,1:=,32:91331a2848d41956aeeec639663b1162,73:Network.Socket.connect: <socket: 26>: does not exist (Connection refused),
```
These are errors related to websocket connection issues.

**Comment by jschaul** [comment]
Maybe you forgot to install the `redis-ephemeral` chart? And/or your gundeck configuration doesn't correctly point to the redis? Or your cannon chart is not correctly installed? Or cannon doesn't correctly advertise its own IP? Or cannon cannot reach redis?

**Comment by ramesh8830** [comment]
Thank you so much. I forgot to install redis-ephemeral chart.  That fixed my problem.

**Comment by lucendio** [comment]
@ramesh8830 In case your issues has been resolved, please close it. Otherwise, please follow up to continue the conversation. Thank you.

**Comment by ramesh8830** [comment]
This is issue got resolved. Thank you.
