### ISSUE TITLE
Audio and Video callings are taking too long to connect

### ISSUE THREAD

**Issue by ramesh8830** [wireapp/wire-server-deploy#180]
Audio and Video callings are taking too long to connect. Did I miss anything in configuration?

**Comment by jschaul** [comment]
What does your configuration and deployment look like? Have you read https://docs.wire.com/understand/restund.html and https://docs.wire.com/how-to/administrate/restund.html as well as https://github.com/wireapp/wire-server-deploy/blob/develop/ansible/restund.yml?

**Comment by ramesh8830** [comment]
Audio or Video calls are only working on same network. Calls are not connecting when we are on two different network.

Is there anything I missed out to config?

All of my configuration is as mentioned on the above documentation

**Comment by lucendio** [comment]
@ramesh8830 In case your issue has been resolved, we'd like to ask you closing it. Otherwise, please follow up on this in order to continue the conversation. Thank you.

**Comment by ramesh8830** [comment]
Its got resolved. Thank you.
