### ISSUE TITLE
Can't deploy cassandra on ubuntu18.04

### ISSUE THREAD

**Issue by kvaps** [wireapp/wire-server-deploy#182]
Hi, `ansible-role-java` ansible role install `openjdk-11-jdk` by default:

https://github.com/geerlingguy/ansible-role-java/blob/master/vars/Ubuntu-18.yml

But cassandra role requires `openjdk-8-jdk` instead.

Solved by specifying exact java version for cassandra and elasticsearch vms in inventory:

```
cassandra1 ansible_host=X.X.X.X java_packages='["openjdk-8-jdk"]'
cassandra2 ansible_host=X.X.X.X java_packages='["openjdk-8-jdk"]'
cassandra3 ansible_host=X.X.X.X java_packages='["openjdk-8-jdk"]'
elasticsearch1 ansible_host=X.X.X.X java_packages='["openjdk-8-jdk"]'
elasticsearch2 ansible_host=X.X.X.X java_packages='["openjdk-8-jdk"]'
elasticsearch3 ansible_host=X.X.X.X java_packages='["openjdk-8-jdk"]'
```

**Comment by lucendio** [comment]
@kvaps In case your issue has been resolved, we'd like to ask you closing it. Otherwise, please follow up on this in order to continue the conversation. Thank you.

**Comment by kvaps** [comment]
Thanks. I have no opportunity to check that right now. I'll reopen this of I will face with this next time.
