### ISSUE TITLE
Restund ports are hardcoded into playbook

### ISSUE THREAD

**Issue by kvaps** [wireapp/wire-server-deploy#183]
It would be nice to specify them via inventory file

**Comment by tiago-loureiro** [comment]
The [restund playbook](https://github.com/wireapp/wire-server-deploy/blob/develop/ansible/restund.yml) is just an example; feel free to adjust that locally to whatever is most convenient for you.

**Comment by lucendio** [comment]
@kvaps In case your issue has been resolved, we'd like to ask you closing it. Otherwise, please follow up on this in order to continue the conversation. Thank you.
