### ISSUE TITLE
SOMETHING WENT WRONG. PLEASE CONTACT YOUR TEAM ADMINISTRATOR FOR DETAILS (ERROR 6).

### ISSUE THREAD

**Issue by ramesh8830** [wireapp/wire-server-deploy#218]
SOMETHING WENT WRONG. PLEASE CONTACT YOUR TEAM ADMINISTRATOR FOR DETAILS (ERROR 6).

Keep getting this error while registering accounts.

Someone please help me fix this problem.

**Comment by lucendio** [comment]
We are happy to help., but we need more context (e.g. reproducible steps, environment information), otherwise it would just be poking around in the dark.

Or you can start to help yourself, since everything is open source :)

* [webapp](https://github.com/wireapp/wire-webapp) (frontend)
* [wire-server](https://github.com/wireapp/wire-server) (backend)
* [wire-server-deploy](https://github.com/wireapp/wire-server-deploy) (deplopyment)
* and even a [guide](https://docs.wire.com)

I would, for example, start by searching for the message phrasing in those code bases.

**Comment by ramesh8830** [comment]
I am in production environment and all pods inside my cluster are running fine without any issues. I am able to load webapp but when I tried to register as user either pro or personal then I am getting an error. Please check the attached screenshot. 
![Capture](https://user-images.githubusercontent.com/56535842/80120555-cdaeb400-85a8-11ea-8623-13d15ef7a56e.PNG)

I saw the reference of error in one of the translations as below

https://github.com/wireapp/wire-web-config-default/blob/master/wire-webapp/content/translation/vi-VN.json
 
`"BackendError.LABEL.SSO_SERVER_ERROR": "Something went wrong. Please contact your team administrator for details (Error 6)."`

**Comment by ramesh8830** [comment]
> 
> 
> I am in production environment and all pods inside my cluster are running fine without any issues. I am able to load webapp but when I tried to register as user either pro or personal then I am getting an error. Please check the attached screenshot.
> ![Capture](https://user-images.githubusercontent.com/56535842/80120555-cdaeb400-85a8-11ea-8623-13d15ef7a56e.PNG)
> 
> I saw the reference of error in one of the translations as below
> 
> https://github.com/wireapp/wire-web-config-default/blob/master/wire-webapp/content/translation/vi-VN.json
> 
> `"BackendError.LABEL.SSO_SERVER_ERROR": "Something went wrong. Please contact your team administrator for details (Error 6)."`

I checked browser console and I am getting below error on the network calls.

`Request URL:https://api.example.com/activate/send
Request Method:POST
Remote Address:x.x.x.x:443
Status Code:
500
Version:HTTP/2
Referrer Policy:same-origin`

**Comment by mheinzel** [comment]
> I checked browser console and I am getting below error on the network calls.

Thanks, this helps to narrow down the issue.

Could you also copy the response body of the network call? This will contain more information about what exactly went wrong.

**Comment by tiago-loureiro** [comment]
> Request URL:https://api.example.com/activate/send Request Method:POST Remote Address:x.x.x.x:443 Status Code: 500 Version:HTTP/2 Referrer Policy:same-origin

Sounds like you are making a request to the default server at `https://api.example.com`. Did you update the backend URLs for the webapp at: https://github.com/wireapp/wire-server-deploy/blob/develop/values/wire-server/demo-values.example.yaml#L157-L160 ?

**Comment by ramesh8830** [comment]
`Request URL:https://api.example.com/activate/send                        `
`Request Method:POST                                                      `
`Remote Address:47.181.37.248:443                                         `
`Status Code: 500                                                         `
`Version:HTTP/2                                                           `
`Referrer Policy:same-origin                                              `
`	                                                                      `
`Response Headers (411 B)	                                              `
`Raw Headers                                                              `
`access-control-allow-credentials : true                                  `
`access-control-allow-origin	: https://app.example.com                 `
`access-control-expose-headers : Request-Id, Location                     `
`content-type : application/json                                          `
`date : Mon, 27 Apr 2020 09:12:56 GMT                                     `
`request-id	: 5fdf514af1527502e4825cc83f68a5ba                            `
`server	: openresty/1.15.8.1                                              `
`strict-transport-security : max-age=15724800; includeSubDomains          `
`X-Firefox-Spdy	: h2                                                      `
`                                                                         `
`Request Headers (384 B)	                                              `
`Raw Headers                                                              `
`Accept	: application/json, text/plain, */*                               `
`Accept-Encoding	: gzip, deflate, br                                   `
`Accept-Language	: en-US,en;q=0.5                                      `
`Connection	: keep-alive                                                  `
`Content-Length	: 49                                                      `
`Content-Type	: application/json;charset=UTF-8                          `
`Host	: api.example.com                                                 `
`Origin	: https://app.example.com                                         `
`TE	: Trailers                                                            `
`User-Agent	: Mozilla/5.0 (Windows NT 10.0; …) Gecko/20100101 Firefox/75.0`

`JSON	                                                       `
`code	:500                                                   `
`message	:"Server Error"                                    `
`label	:"server-error"                                        `
`Response Payload	                                           `
`                                                              `
`1 {"code":500,"message":"Server Error","label":"server-error"}`

![image](https://user-images.githubusercontent.com/56535842/80356782-99344400-8897-11ea-98ce-b14182d74bf3.png)

**Comment by ramesh8830** [comment]
`Request URL:https://api.example.com/activate/send                        `
`Request Method:POST                                                      `
`Remote Address:xx.xx.xx.xx:443                                         `
`Status Code: 500                                                         `
`Version:HTTP/2                                                           `
`Referrer Policy:same-origin                                              `
`	                                                                      `
`Response Headers (411 B)	                                              `
`Raw Headers                                                              `
`access-control-allow-credentials : true                                  `
`access-control-allow-origin	: https://app.example.com                 `
`access-control-expose-headers : Request-Id, Location                     `
`content-type : application/json                                          `
`date : Mon, 27 Apr 2020 09:12:56 GMT                                     `
`request-id	: 5fdf514af1527502e4825cc83f68a5ba                            `
`server	: openresty/1.15.8.1                                              `
`strict-transport-security : max-age=15724800; includeSubDomains          `
`X-Firefox-Spdy	: h2                                                      `
`                                                                         `
`Request Headers (384 B)	                                              `
`Raw Headers                                                              `
`Accept	: application/json, text/plain, */*                               `
`Accept-Encoding	: gzip, deflate, br                                   `
`Accept-Language	: en-US,en;q=0.5                                      `
`Connection	: keep-alive                                                  `
`Content-Length	: 49                                                      `
`Content-Type	: application/json;charset=UTF-8                          `
`Host	: api.example.com                                                 `
`Origin	: https://app.example.com                                         `
`TE	: Trailers                                                            `
`User-Agent	: Mozilla/5.0 (Windows NT 10.0; …) Gecko/20100101 Firefox/75.0`

`JSON	                                                       `
`code	:500                                                   `
`message	:"Server Error"                                    `
`label	:"server-error"                                        `
`Response Payload	                                           `
`                                                              `
`1 {"code":500,"message":"Server Error","label":"server-error"}`
![image](https://user-images.githubusercontent.com/56535842/80356989-e7494780-8897-11ea-8d4b-2a7dbb193757.png)

**Comment by tofutim** [comment]
@ramesh8830 did you ever figure this out? If you do `kubectl logs` on your brig instance it might give you a clue. For me there were issues with the smtp setup.

**Comment by ramesh8830** [comment]
@tofutim For me also it is the issue with smtp setup. Now its working fine but not able to receive email to my different domain email and getting blocked by other server which were sent through wire smtp setup. 

Please help me if you fixed the smtp issues.

**Comment by lucendio** [comment]
I'm sorry but I don't quite understand what you were saying. Can you elaborate on the exact issue that you are still experiencing? If you don't mind, can you also share some more details on your setup and the Helm configuration for Brig.

You might want to take a look at [these information](https://github.com/wireapp/wire-docs/pull/62/files#diff-f8cedcf01e492e50cdcb03257c446523).

**Comment by ramesh8830** [comment]
I am not receiving OTP email when I tried to register on the webapp with my other domain email `(example: ramesh@mydomain.com)`. I am seeing below error when I check mydomain.com mail server logs.

`550 Access denied - Invalid HELO name (See RFC2821 4.1.1.1)`

**Comment by lucendio** [comment]
You might want to take a look at [these information](https://docs.wire.com/how-to/install/troubleshooting.html#i-deployed-the-demo-smtp-but-i-m-not-receiving-any-verification-emails).

**Comment by ramesh8830** [comment]
Hi @lucendio 

I already configured all the needed recordeds (SFP, DKIM, DMARC) for my domain.

**Comment by lucendio** [comment]
Okay. So, can you give an update on what you are currently experiencing? For example, do you still get the same error mentioned in the issue description? Additionally, can you share detailed information and configuration (values, obfuscated secrets) on how your email sending setup currently looks like (e.g. do you use the `demo-smtp`, or maybe AWS SES)?

**Comment by ramesh8830** [comment]
I am not able to configure SMTP with our own smtp credentials. Below is my configuration for smtp.

```
    smtp:
      host: example.com # change this if you want to use your own SMTP server
      port: 465        # change this
      connType: ssl # change this. Possible values: plain|ssl|tls
      username: email@example.com
      passwordFile: /etc/wire/brig/secrets/smtp-password.txt
```
With above configuration brig pods went to CrashLoopBackOff Status. 

```
root@kubenode01:~# kubectl get -n production pods -w
NAME                                       READY   STATUS             RESTARTS   AGE
account-pages-57bcc46977-6tkbn             1/1     Running            0          14m
brig-6fcbccd879-dgms8                      0/1     CrashLoopBackOff   9          14m
brig-6fcbccd879-qt878                      0/1     CrashLoopBackOff   8          14m
brig-6fcbccd879-wcc2s                      0/1     Running            9          14m

```
```
root@kubenode01:kubectl logs -n production -f brig-6fcbccd879-qt878
{"logger":"cassandra.brig","msgs":["I","Known hosts: [datacenter1:rack1:cassandra-ip1:9042,datacenter1:rack1:cassandra-ip2:9042,datacenter1:rack1:cassandra-ip3:9042]"]}
{"logger":"cassandra.brig","msgs":["I","New control connection: datacenter1:rack1:cassandra-ip2:9042#<socket: 11>"]}
```
```
root@kubenode01:~# kubectl describe -n production pod brig-6fcbccd879-qt878
Events:
  Type     Reason     Age                   From                 Message
  ----     ------     ----                  ----                 -------
  Normal   Scheduled  2m47s                 default-scheduler    Successfully assigned production/brig-6fcbccd879-qt878 to kubenode03
  Normal   Created    2m7s (x3 over 2m43s)  kubelet, kubenode03  Created container brig
  Normal   Started    2m6s (x3 over 2m42s)  kubelet, kubenode03  Started container brig
  Warning  Unhealthy  98s (x7 over 2m38s)   kubelet, kubenode03  Readiness probe failed: Get http://10.233.66.165:8080/i/status: dial tcp 10.233.66.165:8080: connect: connection refused
  Normal   Pulled     97s (x4 over 2m43s)   kubelet, kubenode03  Container image "quay.io/wire/brig:0.0.1-pr.2176" already present on machine
  Warning  Unhealthy  97s (x6 over 2m27s)   kubelet, kubenode03  Liveness probe failed: Get http://10.233.66.165:8080/i/status: dial tcp 10.233.66.165:8080: connect: connection refused
  Normal   Killing    97s (x2 over 2m7s)    kubelet, kubenode03  Container brig failed liveness probe, will be restarted
```

With below smtp configuration everything works fine but facing some email delivery issues. I wanted to configure smtp with my own credentials.

```
    smtp:
      host: demo-smtp # change this if you want to use your own SMTP server
      port: 25        # change this
      connType: plain # change this. Possible values: plain|ssl|tls
```
Please help resolve this issue.

**Comment by lucendio** [comment]
Okay, there are a couple of things that come to my mind:

Unfortunately the logs are not very helpful since nothing is shown related to SMTP.

1. You dont need `passwordFile` changing it might even be dangerous, because it is not propagated into the deployment and volumeMounts
2. did you define your password in the secrets.yaml, respectively: `brig.secrets.smtpPassword`?
3. did you set `brig.config.useSES: false`?
4. check whether you rmail server uses the full email address as the username or just the part before the `@`

**Comment by ramesh8830** [comment]
> 1. You dont need `passwordFile` changing it might even be dangerous, because it is not propagated into the deployment and volumeMounts

I didn't change the passwordFile, I just gave the path in the values.yaml file.

> 2. did you define your password in the secrets.yaml, respectively: `brig.secrets.smtpPassword`?

Yes. I defined the email password in secrets.yaml file under `brig.secrets.smtpPassword`

> 3. did you set `brig.config.useSES: false`?

Yes. I did configured as false

> 4. check whether you rmail server uses the full email address as the username or just the part before the `@`

My email server use full email address as username. It won't accept without '@example.com'

**Comment by lucendio** [comment]
Thank you. So the last things that come to my mind, are

1. Test a totally different mail provider (e.g. instead of gmail, something else) and see if it behaves differently
2. change `connType`
3. Unlikely, but anyway: re-deploy / start from scratch and see if it's reproducible

**Comment by mtahle** [comment]
> @tofutim For me also it is the issue with smtp setup. Now its working fine but not able to receive email to my different domain email and getting blocked by other server which were sent through wire smtp setup.
> 
> Please help me if you fixed the smtp issues.

Hello @ramesh8830 ,

I have the same issue with registration, could you please tell me how you solve yours?

**Comment by ramesh8830** [comment]
Please check your smtp or brig. You will find the issue
