### ISSUE TITLE
Having issue while configuring real AWS services

### ISSUE THREAD

**Issue by ramesh8830** [wireapp/wire-server-deploy#228]
`root@kubenode01:~# kubectl -n production logs -f brig-7c5547f7db-dmg6q
{"logger":"cassandra.brig","msgs":["I","Known hosts: [datacenter1:rack1:ip1:9042,datacenter1:rack1:ip2:9042,datacenter1:rack1:ip3:9042]"]}
{"logger":"cassandra.brig","msgs":["I","New control connection: datacenter1:rack1:ip3:9042#<socket: 11>"]}
service: GeneralError (TransportError (HttpExceptionRequest Request {
  host                 = "sqs.us-east-1.amazonaws.com"
  port                 = 443
  secure               = True
  requestHeaders       = [("Host","sqs.us-east-1.amazonaws.com"),("X-Amz-Date","20200418T154336Z"),("X-Amz-Content-SHA256","a1bccad704dcd70c26894d153950204cc9abd1acac42904739730e1de32c5458"),("Content-Type","application/x-www-form-urlencoded; charset=utf-8"),("Authorization","<REDACTED>")]
  path                 = "/"
  queryString          = ""
  method               = "POST"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 0
  responseTimeout      = ResponseTimeoutMicro 70000000
  requestVersion       = HTTP/1.1
}
 (ConnectionFailure Network.Socket.connect: <socket: 16>: does not exist (Host is unreachable))))
`
brig and gundeck pods are getting failed.

is it something wrong with configuration?

**Comment by orandev** [comment]
Do your pods have direct access to the Internet or do they need to go through a proxy?

**Comment by arianvp** [comment]
Sounds like your pods can not access the internet. This is a misconfiguration in your kubernetes cluster.  What happens when you run:


```
$ kubectl run -it --rm --restart=Never busybox
# ping sqs.us-east-1.amazonaws.com
```

?

**Comment by ramesh8830** [comment]
@orandev I have direct access to the Internet. I am able to access the webapps when I use the fake aws. Only pods are failing while deploying with real aws values.

@arianvp Pods has internet access. 

`kubectl run -it --rm --restart=Never busybox
Error: required flag(s) "image" not set`

`ping sqs.us-east-1.amazonaws.com
PING queue.amazonaws.com (52.46.136.160) 56(84) bytes of data.
64 bytes from 52.46.136.160 (52.46.136.160): icmp_seq=1 ttl=235 time=64.4 ms
64 bytes from 52.46.136.160 (52.46.136.160): icmp_seq=2 ttl=235 time=64.9 ms
64 bytes from 52.46.136.160 (52.46.136.160): icmp_seq=3 ttl=235 time=64.1 ms
64 bytes from 52.46.136.160 (52.46.136.160): icmp_seq=4 ttl=235 time=64.7 ms
64 bytes from 52.46.136.160 (52.46.136.160): icmp_seq=5 ttl=235 time=65.3 ms
64 bytes from 52.46.136.160 (52.46.136.160): icmp_seq=6 ttl=235 time=69.8 ms
64 bytes from 52.46.136.160 (52.46.136.160): icmp_seq=7 ttl=235 time=63.5 ms
64 bytes from 52.46.136.160 (52.46.136.160): icmp_seq=8 ttl=235 time=63.6 ms
64 bytes from 52.46.136.160 (52.46.136.160): icmp_seq=9 ttl=235 time=64.8 ms
64 bytes from 52.46.136.160 (52.46.136.160): icmp_seq=10 ttl=235 time=63.8 ms
`

**Comment by lucendio** [comment]
@ramesh8830 In case your issue has been resolved, we'd like to ask you closing it. Otherwise, please follow up on this in order to continue the conversation. Thank you.

**Comment by ramesh8830** [comment]
Its got resolved. Thank you..
