### ISSUE TITLE
Image or file sharing not working with minio

### ISSUE THREAD

**Issue by ramesh8830** [wireapp/wire-server-deploy#248]
Hi,

I am unable to share any files or images on webapp. I configured minio for server setup and getting below error in cargohold pod.

`{   host                = "minio-external" `  																													
`	port                 = 9000   `
`	secure               = False   `
`	requestHeaders       = [("Date","Thu, 30 Apr 2020 14:52:37 GMT"),("Content-Type","application/octet-stream"),("Content-MD5","FQq4x/fX/F7FUwQBY4wkYQ=="),("Authorization","<REDACTED>"),("x-amz-meta-user","c64da7b6-71bc-4df4-94bf-ca22c80248d9"),("Expect","100-continue")]   `
`	path                 = "/assets/v3/eternal/71d4d79e-c703-4b14-ba29-f969d6df3be8"   `
`	queryString          = ""   `
`	method               = "PUT"   `
`	proxy                = Nothing   `
`	rawBody              = False   `
`	redirectCount        = 10   `
`	responseTimeout      = ResponseTimeoutDefault   `
`	requestVersion       = HTTP/1.1 }  ResponseTimeout`

Please help me resolve this error.

**Comment by jschaul** [comment]
Can you verify the bucket exists on minio? I.e, has [this part](https://github.com/wireapp/wire-server-deploy/blob/develop/ansible/minio.yml#L40-L60) successfully executed? Is https://github.com/wireapp/wire-server-deploy/blob/develop/values/wire-server/prod-values.example.yaml#L111-L113 correctly configured? Can `cargohold` reach minio? Is the configured bucket name in helm matching the bucket name create in minio?

**Comment by ramesh8830** [comment]
Hi @jschaul 

I partially fixed this problem. Now the files being uploaded to minio buckets but can't see same file/images on the chat windows.

Please find the attached screenshots.

![chat window](https://user-images.githubusercontent.com/56535842/81023623-9d132800-8e8e-11ea-9098-12170163229b.PNG)
![minio](https://user-images.githubusercontent.com/56535842/81023625-9dabbe80-8e8e-11ea-810f-ad6ddd5cca9d.PNG)

**Comment by tiago-loureiro** [comment]
Do you see any errors on the webapp when trying to upload/download the images? Have a look at the [CSP headers](https://github.com/wireapp/wire-server-deploy/blob/develop/values/wire-server/prod-values.example.yaml#L232-L243) - if they are not set for your installation correctly, you are likely to be unable to display them on the app

**Comment by ramesh8830** [comment]
Below is the one of the error i am seeing on the browser console under network.

`Request URL: https://assets.example.com/assets/v3/eternal/27c8e061-cf9e-468c-940b-fd8d9aa34b52?Expires=1588698027&AWSAccessKeyId=5UKJhtzzmxcX6WVaEu4N&SignatureMethod=HmacSHA256&Signature=y19mhQhlWpJPUKnQKiRoVZ4m6WA%3D`
`Request Method: GET`
`Status Code: 403 `
`Remote Address: xx.xx.xx.xx:443`
`Referrer Policy: same-origin`
`access-control-allow-credentials: true`
`access-control-allow-origin: *`
`access-control-expose-headers: Date, Etag, Server, Connection, Accept-Ranges, Content-Range, Content-Encoding, Content-Length, Content-Type, X-Amz*, X-Amz*, *`
`content-encoding: gzip`
`content-security-policy: block-all-mixed-content`
`content-type: application/xml`
`date: Tue, 05 May 2020 16:55:28 GMT`
`server: openresty/1.15.8.1`
`status: 403`
`strict-transport-security: max-age=15724800; includeSubDomains`
`vary: Accept-Encoding`
`vary: Origin`
`x-amz-request-id: 160C302A9B6F8A1E`
`x-xss-protection: 1; mode=block`
`:authority: assets.example.com`
`:method: GET`
`:path: /assets/v3/eternal/27c8e061-cf9e-468c-940b-fd8d9aa34b52?Expires=1588698027&AWSAccessKeyId=5UKJhtzzmxcX6WVaEu4N&SignatureMethod=HmacSHA256&Signature=y19mhQhlWpJPUKnQKiRoVZ4m6WA%3D`
`:scheme: https`
`accept: */*`
`accept-encoding: gzip, deflate, br`
`accept-language: en-US,en;q=0.9,te;q=0.8`
`origin: null`
`sec-fetch-dest: empty`
`sec-fetch-mode: cors`
`sec-fetch-site: same-site`
`user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36`
`Expires: 1588698027`
`AWSAccessKeyId: 5UKJhtzzmxcX6WVaEu4N`
`SignatureMethod: HmacSHA256`
`Signature: y19mhQhlWpJPUKnQKiRoVZ4m6WA=`

`<Error><Code>InvalidAccessKeyId</Code><Message>The access key ID you provided does not exist in our records.</Message><Key>v3/eternal/27c8e061-cf9e-468c-940b-fd8d9aa34b52</Key><BucketName>assets</BucketName><Resource>/assets/v3/eternal/27c8e061-cf9e-468c-940b-fd8d9aa34b52</Resource><RequestId>160C302A9B6F8A1E</RequestId><HostId>f29a4642-8d82-4eb7-a9c5-21476aea1df6</HostId></Error>`

Below is the config for CSP headers

![image](https://user-images.githubusercontent.com/56535842/81094641-718d4d80-8f21-11ea-9292-2891b0eb8749.png)

Below is Cargohold values

![image](https://user-images.githubusercontent.com/56535842/81094710-8c5fc200-8f21-11ea-9b8d-c8f67e8529f7.png)

I even tried passing same access key and secret key to fake-aws-s3 charts which are same as minio access and secret key but not luck.

**Comment by ramesh8830** [comment]
I managed fix the few issues with access key and secret key. Now my problem is, files/images shared are not getting downloaded to fake s3 bucket which is for download end point(assets.example.com). If manually ssh into fake s3 bucket container and put the files(downloaded from minio external buckets), then the files/images showing on the chat.

Please help me resolve the issue.

**Comment by ramesh8830** [comment]
Can someone please explain how to cargohold works?
![image](https://user-images.githubusercontent.com/56535842/82124416-889f2b80-97bc-11ea-8981-b7871df04458.png)

For me, shared files in the chat being uploaded to minio externals but not being downloaded to s3DownloadEndpoint to reflect on the chat window. 

Please help me

**Comment by lucendio** [comment]
Hi @ramesh8830 

looking at your cargohold configuration, I assume you deployed minio somewhere outside of the k8s cluster, let's say, a dedicated virtual machine or something. Is that correct?
Furthermore, you probably configured & deployed ingress, similar to how it's described in the [docs](https://docs.wire.com/how-to/install/helm.html#how-to-direct-traffic-to-your-cluster). Is that correct?
Lastly, can you provide us please with the `values.yaml` file, that you used for deploying `nginx-ingress-services` via Helm?

**Comment by ramesh8830** [comment]
Hi @lucendio 

> looking at your cargohold configuration, I assume you deployed minio somewhere outside of the k8s cluster, let's say, a dedicated virtual machine or something. Is that correct?
Yes. Dedicated VMs for minio

> Furthermore, you probably configured & deployed ingress, similar to how it's described in the docs. Is that correct?
Correct

> Lastly, can you provide us please with the values.yaml file, that you used for deploying nginx-ingress-services via Helm?

`teamSettings:
  enabled: false
accountPages:
  enabled: true
tls:
  enabled: true

config:
  dns:
    https: api.example.com
    ssl: wss.example.com
    webapp: app.example.com
    fakeS3: assets.example.com
    teamSettings: teams.example.com
    accountPages: account.example.com
service:
  s3:
    externalPort: 9000
    serviceName: minio-external
    externallyCreated: true`


`Request URL: https://assets.example.com/assets/v3/eternal/6d87d64d-984b-4981-87eb-ddda1dcf36ec?Expires=1589979489&AWSAccessKeyId=5UKJhtzzmxcX6WVaEu4N&SignatureMethod=HmacSHA256&Signature=keMFtwu5W84QbzD6Rs%2Bgfwolxdw%3D`
`Request Method: GET`
`Status Code: 404 `
`Remote Address: xx.xx.xx.xx:443`
`Referrer Policy: same-origin`

`<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>v3/eternal/6d87d64d-984b-4981-87eb-ddda1dcf36ec</Key><BucketName>assets</BucketName><Resource>/assets/v3/eternal/6d87d64d-984b-4981-87eb-ddda1dcf36ec</Resource><RequestId>1610BDA6293E1B6A</RequestId><HostId>3414d4fd-c97e-4edc-b3d2-f8df0911c49b</HostId></Error>`

**Comment by lucendio** [comment]
> I managed to fix the few issues with access key and secret key. Now my problem is, files/images shared are not getting downloaded to fake s3 bucket which is for download end point(assets.example.com). If manually ssh into fake s3 bucket container and put the files(downloaded from minio external buckets), then the files/images showing on the chat.

This sounds a bit confusing to me. You said, you are running minio-external, but at the same time, you have a fake s3 bucket container that you are ssh-int into? Can you clarify this, please.

You may want to try debugging `assets.example.com` from the outside, too. Since it's minio, you can takuse the minio-client and configure it accordingly. You also provisioned minio yourself, so you have some credentials for it, too.

Furthermore, the documentation on the [Assets API](https://github.com/wearezeta/backend-api-docs/wiki/API-Assets) might give you a better understanding on how it works.

**Comment by ramesh8830** [comment]
Hi @lucendio 

Cargohold configuration has two different end points. 

1. 's3Endpoint: http://minio-external:9000'
Whatever the files we shared over the chat are stored into minio-externals which are dedicated VMs.

2. 's3DownloadEndpoint: https://assets.example.com'
assets.example.com configured to fake-s3 container (which is a minio container) as per the deployment scripts and without fake-s3 chart the deployment is being failed. As per my understanding, whatever files are present in the minio-externals also to be present the fake-s3 which is configure for assets.example.com to preview or download shared files on chat. I don't see anything inside fake-s3 container for the configured location, that is the reason i am getting below error.

`<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>v3/eternal/6d87d64d-984b-4981-87eb-ddda1dcf36ec</Key><BucketName>assets</BucketName><Resource>/assets/v3/eternal/6d87d64d-984b-4981-87eb-ddda1dcf36ec</Resource><RequestId>1610BDA6293E1B6A</RequestId><HostId>3414d4fd-c97e-4edc-b3d2-f8df0911c49b</HostId></Error>`

What I tried is I logged into minio-externals from the browser and downloaded shared files and then placed the same files inside the fake-s3 container at the location '/assets/v3/eternal/'. Then I can able to preview the exact images/files on the chat and can able to download it.

So how to get the shared files downloaded to fake-s3 container as well. am I missed configuration or am I not configured properly or am  I completely misunderstood configuration?

Please help me.

**Comment by jschaul** [comment]
> assets.example.com configured to fake-s3 container

this is the problem. You need to point both to the same storage, i.e. in your case, the real minio instances via minio-external.

remove `fake-s3` helm chart from your installation, it's not needed. If you install minio separately, then you don't need it. It's used only in the demo installation (for people only wanting to run everything inside a pod in an ephemeral way).

**Comment by ramesh8830** [comment]
Thank you so much. It worked!!

**Comment by ramesh8830** [comment]
Hi,

I have got another issue now. I am on production setup with 3 minio servers (dedicated VM's). The files/images being shared on the chat are stored randomly over the 3 minio servers. But only few  of the images are getting visible on the chat window and others showing blank. 

are the minio configuration not supposed to store the shared files on all 3 minio servers instead of saving on one random server?

![image](https://user-images.githubusercontent.com/56535842/83700974-f3a68a00-a625-11ea-8427-c6ecd3f4e8b8.png)

Can you please me on this one?

**Comment by lucendio** [comment]
@ramesh8830 can you please open another issue for this, since it' not the same case - same technology but probably not the same cause. And then, pleas add browser console and network logs. Thank you.
