### ISSUE TITLE
Webapp stucked

### ISSUE THREAD

**Issue by rahulit1991** [wireapp/wire-server-deploy#274]
@lucendio, I am facing an webapp stuck with below screenshot.

![image](https://user-images.githubusercontent.com/64314085/82699452-4ed19780-9c8a-11ea-93a3-1146e1ffb9e0.png)

i am not able click on "Accept" or "No thanks". I tried with all browser. I inspect element and it shows this error:

```
Request URL:https://nginz-https.domain.com/self/consent
Request Method:PUT
Remote Address:52.201.26.92:443
Status Code:
404
Version:HTTP/2
Referrer Policy:same-origin
```

Also i check try check nginz pod logs.
**kubectl logs -f nginz-85cdfdb8df-rsvc8 -c nginz** 

```
172.31.0.81 - "25/May/2020:03:45:58 +0000" "OPTIONS /self/consent HTTP/1.1" 204 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" 172.31.8.250 290 0.000 - - - - fbac564e77dc4b29f0717f355f565680 
172.31.8.250 - "25/May/2020:03:45:58 +0000" "PUT /self/consent HTTP/1.1" 404 106 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" 172.31.8.250 290 0.001 0.000 - 46a60720-96c0-40af-ba79-6866db2c94fc 1842137572099248510 e160fdac8f7290e75d4bd9c8067009ec 
```

Can you please me to why i am facing this unknown issue? i tried with remove and setup things again. but not get any success.

Thanks You

**Comment by tiago-loureiro** [comment]
Hi @rahulit1991 

You will need to set [this environment variable](https://github.com/wireapp/wire-server-deploy/blob/develop/values/wire-server/prod-values.example.yaml#L223) in your env.

More documentation on environment variables can be found [here](https://github.com/wireapp/wire-web-config-default/blob/master/wire-webapp/.env.defaults)

**Comment by rahulit1991** [comment]
@tiago-loureiro thanks you. issue resolved. appreciate for you help.
