### ISSUE TITLE
Shared Images not being displayed on the chat

### ISSUE THREAD

**Issue by ramesh8830** [wireapp/wire-server-deploy#282]
Hi,

I am on production setup with 3 minio VM's. Some of the images being shared on the chat are not displayed or downloadable. 

Lets say I have shared three images at a time on my chat, out 3 only 1 images is visible on the chat and remaining 2 showing as blank frames. as show below.

![image](https://user-images.githubusercontent.com/56535842/83801758-50a64c80-a6c7-11ea-9c22-7f9e96dce789.png)

Below are the network logs.

```
Request URL: https://assets.example.com/assets/v3/eternal/4899444b-3032-4851-95cd-102baa0d05d3?Expires=1591297623&AWSAccessKeyId=koUSmGaX6YumkLTnIN&SignatureMethod=HmacSHA256&Signature=IQO5HUkZP8YMNpB%2F8z9EpEL4GQo%3D
Request Method: GET
Status Code: 404 
Remote Address: xx.xx.xx.xx:443
Referrer Policy: same-origin
```
`<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>v3/eternal/4899444b-3032-4851-95cd-102baa0d05d3</Key><BucketName>assets</BucketName><Resource>/assets/v3/eternal/4899444b-3032-4851-95cd-102baa0d05d3</Resource><RequestId>16156C7C127B2C2B</RequestId><HostId>a9e6c92a-1d42-419a-aa5b-038d619a6b23</HostId></Error>`

```
Request URL: https://assets.example.com/assets/v3/eternal/f928f49d-8a7e-4967-a4a8-03af5ac9e2cb?Expires=1591297628&AWSAccessKeyId=koUSmGaX6YumkLTnIN&SignatureMethod=HmacSHA256&Signature=F7rNGF%2BKJNo1El%2BXMYKxCAVQU0A%3D
Request Method: GET
Status Code: 404 
Remote Address: xx.xx.xx.xx:443
Referrer Policy: same-origin
```

`<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>v3/eternal/f928f49d-8a7e-4967-a4a8-03af5ac9e2cb</Key><BucketName>assets</BucketName><Resource>/assets/v3/eternal/f928f49d-8a7e-4967-a4a8-03af5ac9e2cb</Resource><RequestId>16156C7D7C826400</RequestId><HostId>d2bb6d4f-ce77-4a4f-a9df-f5c9e696872b</HostId></Error>`

Please see below bucket screenshot which shows assets are present inside the bucket.

![image](https://user-images.githubusercontent.com/56535842/83802438-61a38d80-a6c8-11ea-9f61-254f55e57b28.png)

Sometimes, files being stored across all 3 minio buckets randomly like few in one bucket and few in others. In that case also all images or files are not being displayed on the chat

Please help me resolve this issue.

**Comment by lucendio** [comment]
Hi @ramesh8830,

From the information you have shared, it is not really possible to reproduce the issue. Without this, we have to assume, that the root cause lies in minio. For which this is not the right place to be addressed.

As a side note, you may want to look into `Service` and `Endpoint` configuration on K8s, since you mentioned 3 minio VMs. With this setup, the traffic usually goes through K8s (see `charts/minio-external`.

**Comment by ramesh8830** [comment]
The same thing is happening when i use the amazon s3 bucket as well.

**Comment by lucendio** [comment]
> The same thing is happening when i use the amazon s3 bucket as well.

You mean, random assets are not showing up and result in 404 in the browser network debugger? Do you see an pattern in that? Do you use the latest release of wire-server-deploy (you may want to adjust the frontends according to this https://github.com/wireapp/wire-server-deploy/pull/286?

**Comment by ramesh8830** [comment]
I don't see any pattern and even when i reload page previously shown images are going blank. Looks like assets are not being downloaded to local. 

I already using latest frontends.

**Comment by lucendio** [comment]
Great, random behaviour. This is hard to hunt down. My last two ideas would be 

1. If possible, try to switch to s3 (or any other object storage)
2. try to redeploy form scratch to see id this behaviour consistent

I'm sorry that I can't offer more here.

**Comment by ramesh8830** [comment]
Just redepolyed the with s3 and having same issue. Can't see any images or download any files from the webapp. Below are my CSP headers.

```
    CSP_EXTRA_CONNECT_SRC: "https://*.example.com, https://api.raygun.io, wss://wss.example.com, https://s3.us-east-1.amazonaws.com, https://*.giphy.com"
    CSP_EXTRA_IMG_SRC: "https://s3.us-east-1.amazonaws.com, https://*.example.com, https://*.giphy.com"
    CSP_EXTRA_SCRIPT_SRC: "https://*.example.com, https://api.raygun.io, https://s3.us-east-1.amazonaws.com, https://*.giphy.com"
    CSP_EXTRA_DEFAULT_SRC: "https://*.example.com"
    CSP_EXTRA_FONT_SRC: "https://*.example.com"
    CSP_EXTRA_FRAME_SRC: "https://*.example.com"
    CSP_EXTRA_MANIFEST_SRC: "https://*.example.com"
    CSP_EXTRA_OBJECT_SRC: "https://*.example.com"
    CSP_EXTRA_MEDIA_SRC: "https://s3.us-east-1.amazonaws.com, https://*.giphy.com"
    CSP_EXTRA_PREFETCH_SRC: "https://*.example.com"
    CSP_EXTRA_STYLE_SRC: "https://*.example.com"
    CSP_EXTRA_WORKER_SRC: "https://*.example.com"
```

anything wrong with my CSP headers?
