### ISSUE TITLE
images or file in able to download or view

### ISSUE THREAD

**Issue by rahulit1991** [wireapp/wire-server-deploy#284]
Hello,

i just deployed fresh wire server demo on GCP. after successfully installed. i am able to login and chat message. working fine as expected. but when i upload some file or image. its not visible in chat on both side. its show like below screenshot.

![image](https://user-images.githubusercontent.com/64314085/84264345-a606b180-ab3e-11ea-9bda-d4da331278ac.png)

Also i see some console error. there are some errors. as in below screenshot:

![image](https://user-images.githubusercontent.com/64314085/84264623-26c5ad80-ab3f-11ea-861c-7cbe6de11237.png)

can you please help me why i am facing this issue. as just with fresh demo with dummy bucket?

FYI, i am fine with disclose domain name here as this is my test server so i will demolish it after all things working as expected.

Thank you

**Comment by ramesh8830** [comment]
I am also facing same issue and posted under https://github.com/wireapp/wire-server-deploy/issues/282 couple of days back.

**Comment by lucendio** [comment]
Hi @rahulit1991,

you may want to look into this https://github.com/wireapp/wire-server-deploy/issues/248 to see if you can find anything useful. From what you have shared, it looks like you are missing some CSP configuration, set bu environment variables for the webapp.

**Comment by rahulit1991** [comment]
@lucendio thanks for your reply. yes. i have added all CSP configuration. you can check values.yml file here.
[values.yaml.zip](https://github.com/wireapp/wire-server-deploy/files/4786659/values.yaml.zip)

Thank you

**Comment by lucendio** [comment]
From what is says in the browser network logs it is indeed a CSP issue. Or have the logs/errors changed?

You may want to try another browser. You might also want to try a newer version of the webapp (see https://github.com/wireapp/wire-server-deploy/pull/286), although I expect no significat change from this.

**Comment by rahulit1991** [comment]
@lucendio , Hello,
I update my webapp with latest version.i switched my object storage from demo-s3 to real aws service. lots of CSP error i resolved using below configuration:
![image](https://user-images.githubusercontent.com/64314085/85132518-9251fe00-b256-11ea-89c8-f81e7d8b4fcf.png)

i configured real aws service with below cargohold:
![image](https://user-images.githubusercontent.com/64314085/85132646-d3e2a900-b256-11ea-9d41-625f5b439bc6.png)

i can see document uploaded successfully on aws s3. Also there is no error logs in cargohold pods other than s3 upload logs as below:
![image](https://user-images.githubusercontent.com/64314085/85132973-769b2780-b257-11ea-96cb-d71a9e25ccb6.png)

Here you can find error in browser. i tried with all browser face same issue.

![Screenshot 2020-06-19 at 6 07 00 PM](https://user-images.githubusercontent.com/64314085/85133535-7ea79700-b258-11ea-9a70-815668525aa9.png)

The issue is that i can't see/download files/images which i uploaded or receive from another user. 
![image](https://user-images.githubusercontent.com/64314085/85133768-f2e23a80-b258-11ea-831a-7591b0c5ab32.png)

Can you please help me to resolve this issue. as i tried all solution but did not get success.

**Comment by rahulit1991** [comment]
@lucendio i think this will help you to figure out issue. FYI, i added CORS configuration in S3 bucket as below:

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```
 
![Screenshot 2020-06-19 at 7 37 35 PM](https://user-images.githubusercontent.com/64314085/85141533-89682900-b264-11ea-9b24-29d5f6e54a85.png)

**Comment by lucendio** [comment]
That looks a bit funky. If you are using s3 and you are serving directly from there, you should not add `s3DownloadEndpoint`. This configuration is meant to either obfuscate the fact that s3 is used for assets, or when you use minio. In case of the latter, some k8s resources namely `Ingress` takes care of rerouting the request with the help of a `Service` and an `Endpoint` ([exp](https://github.com/wireapp/wire-server-deploy/blob/develop/charts/minio-external/templates/endpoint.yaml))

**Comment by rahulpatel1991** [comment]
@lucendio thanks for reply. So you mean i can't setting up S3 directly to serve and store content? Or i need to change configuration. Can you please let me know what things i did wrong and what things i should change fo things working?

Your help is really appreciated. As i am stucked in this issue from last 2 week.

**Comment by rahulit1991** [comment]
@lucendio  thanks for reply. 

I want to make solution with s3 only not minio. Can you please let me know what things i did wrong and what things i should change fo things working?

Should i need to add configuration in nginx ingress for external minio as s3 endpoint?

Your help is really appreciated. As i am stucked in this issue from last 2 week.

**Comment by lucendio** [comment]
Great to hear, that you are making progress. As the browser logs clearly state, you are still facing a CSP issue, that needs to be solved. The two locations for this are:

* `wire-server/vaules.yaml` --> environment variables for `webapp`
* s3 policies

As you solved your initial issue. I would like to go ahead and close this here, if you don't object.

A side note that you might find useful: it would be way easier to redact things, if you would just copy&past text instead of screenshooting code.

**Comment by rahulit1991** [comment]
sure i will follow this for upcoming issues. thanks for your support.
