### ISSUE TITLE
Cannot register with email on iOS app on demo wire server.

### ISSUE THREAD

**Issue by smoesai** [wireapp/wire-server-deploy#296]
* [x] I have seen https://docs.wire.com/ and https://github.com/wireapp/wire-server-deploy - the documentation there does not answer my question.

Hello everyone,

I am trying to setup the wire server demo. I have installed everything and in the app I keep getting this error when I want to register by email. I don't know where it comes from and where to look. Below the logs from debugging the iOS code.

Transcoder: <WireSyncEngine.RegistationCredentialVerificationStrategy> 0x600001423e40
2020-06-24 09:29:34.151584+0200 Wire[1042:25018] [Network] Nil request generated
2020-06-24 09:29:34.278690+0200 Wire[1042:25025] [Network] [Unauthenticated] <---- Response: <ZMTransportResponse: 0x600003707250> 404 {
    Connection = "keep-alive";
    "Content-Encoding" = gzip;
    "Content-Type" = "text/html";
    Date = "Wed, 24 Jun 2020 07:29:34 GMT";
    Server = "nginx/1.14.0 (Ubuntu)";
    "Transfer-Encoding" = Identity;
} (null)
2020-06-24 09:29:34.281758+0200 Wire[1042:25025] [Authentication] Event handling manager received event: registrationError(Error Domain=ZMUserSession Code=1 "Something went wrong, please try again" UserInfo={NSLocalizedDescription=Something went wrong, please try again})
2020-06-24 09:29:34.283132+0200 Wire[1042:25025] [Authentication] Handing event using RegistrationActivationErrorHandler, and 2 actions.
2020-06-24 09:29:34.291965+0200 Wire[1042:25025] [Network] Nil request generated

I get this error as soon as I write my email address and press the button to go to the next step. Can I get some help with this please..?
![Screenshot 2020-06-23 at 23 24 39](https://user-images.githubusercontent.com/29788467/85516504-8d969c80-b5fe-11ea-8d7e-e513344045ee.png)
![Screenshot 2020-06-24 at 09 39 03](https://user-images.githubusercontent.com/29788467/85516535-97b89b00-b5fe-11ea-83da-83ca87ba82c4.png)
![Screenshot 2020-06-24 at 09 39 40](https://user-images.githubusercontent.com/29788467/85516591-a8691100-b5fe-11ea-8963-ffcd9dcae6f4.png)

## Context:

Here are my pods:

NAMESPACE     NAME                                                       READY   STATUS      RESTARTS   AGE
default       brig-76555c4c98-9tl4n                                      1/1     Running     5          30m
default       cannon-0                                                   0/1     Pending     0          30m
default       cargohold-b5548fccc-fx9f9                                  1/1     Running     1          30m
default       cassandra-ephemeral-0                                      1/1     Running     5          4h
default       cassandra-migrations-lt8st                                 0/1     Completed   0          30m
default       demo-smtp-84b7b85ff6-rfwt8                                 1/1     Running     5          3h56m
default       elasticsearch-ephemeral-8545b66bcc-hs7w4                   1/1     Running     5          4h
default       elasticsearch-index-create-fcdpp                           0/1     Completed   0          30m
default       fake-aws-dynamodb-84f87cd86b-2tx6x                         2/2     Running     2          44m
default       fake-aws-s3-5c846cb5d8-c5422                               1/1     Running     1          44m
default       fake-aws-s3-reaper-7c6d9cddd6-7rtxv                        1/1     Running     1          44m
default       fake-aws-sns-5c56774d95-zmmmt                              2/2     Running     2          44m
default       fake-aws-sqs-554bbc684d-44x7s                              2/2     Running     2          44m
default       galley-695f5f9dd4-w9d5k                                    1/1     Running     5          30m
default       gundeck-5887f9b88-svdqq                                    1/1     Running     5          30m
default       nginx-ingress-controller-568d5fb76d-4rkxk                  1/1     Running     5          3h54m
default       nginx-ingress-controller-controller-vbknf                  1/1     Running     5          3h9m
default       nginx-ingress-controller-default-backend-9866b44fd-r2sbb   1/1     Running     5          3h9m
default       nginx-ingress-default-backend-5654878679-jzzfx             1/1     Running     5          3h54m
default       nginz-56d675d49b-9z9f5                                     0/2     Pending     0          30m
default       redis-ephemeral-69bb4885bb-68sgd                           1/1     Running     5          4h
default       webapp-7db69c56fb-jrgbg                                    0/1     Pending     0          30m
kube-system   coredns-56bc6b976d-c5n26                                   0/1     Pending     0          4h8m
kube-system   coredns-56bc6b976d-qc6wx                                   1/1     Running     5          4h9m
kube-system   dns-autoscaler-56c969bdb8-8gjrf                            1/1     Running     5          4h8m
kube-system   kube-apiserver-kubenode01                                  1/1     Running     5          4h9m
kube-system   kube-controller-manager-kubenode01                         1/1     Running     5          4h9m
kube-system   kube-flannel-2mfvq                                         2/2     Running     14         4h9m
kube-system   kube-proxy-vcbwd                                           1/1     Running     5          4h9m
kube-system   kube-scheduler-kubenode01                                  1/1     Running     5          4h9m
kube-system   kubernetes-dashboard-6c7466966c-nmv2c                      1/1     Running     5          4h8m
kube-system   nodelocaldns-fvl7q                                         1/1     Running     5          4h8m
kube-system   tiller-deploy-8458f6c667-m5r4g                             1/1     Running     1          52m

I user kubernetes to install the wire-server.

### How many servers are involved?

Just one. I am running the demo version.

> E.g Server A has component X and server B has component Y

### Provide details about networking

> We don't need to know any specific IP address, but it helps if you provide information whether an IP is ipv4 or ipv6, whether is is publicly reachable from the global internet or not, and if you installed any component of wire-server, which network interfaces are processes listening on?

### How did you configure wire-server?

> *Note: only the configuration from helm charts in wire-server-deploy is what we support, like [these defaults](https://github.com/wireapp/wire-server-deploy/blob/develop/charts/brig/values.yaml) applied [here](https://github.com/wireapp/wire-server-deploy/blob/develop/charts/brig/templates/configmap.yaml) in the case of `brig`. If you have used other configuration files, please post them (or the relevant parts of them).*
> Did you use the helm charts from wire-server-deploy?
No, everything is default
> Did you use and adapt configuration files from wire-server? If so, which ones?
I only followed the steps from the manual.
> Are there any overrides?
No, everything is default.

**Comment by lucendio** [comment]
I believe your issue is better suited to be addressed here, which is why I moved it, just fyi :)

So, there are a couple of things, that come to mind:

* you have a couple of pending pods. this is usually a  sign or either K8s is not able to pull container images or not enough resource being available so that the kube-scheduler can actually schedule the workload.
* register usually means email, even though the `demo-smtp` is running, you might need to do some [DNS magic](https://docs.wire.com/how-to/install/troubleshooting.html#i-deployed-the-demo-smtp-but-i-m-not-receiving-any-verification-emails)

If you require further assistance, I'd like to ask you to use one of our [issue temples](https://github.com/wireapp/wire-server-deploy/tree/develop/.github/ISSUE_TEMPLATE) in this repository.

**Comment by smoesai** [comment]
![Screenshot 2020-06-24 at 20 47 43](https://user-images.githubusercontent.com/29788467/85615085-f8c28c00-b65b-11ea-9f49-02ce3365d7aa.png)
This is also what I cannot understand. Why do I keep getting this Blacklist download returned status code 404 error..

**Comment by smoesai** [comment]
Basic information
On-premises:
Cloud-Provider:

_VPS:
4 CPU cores
8 GB RAM
200 GB disk space
UNLIMITED traffic
200Mbit/s port
Root access
1 IP address included
/64 IPv6 network included_

Installation type:

Demo. On only one server (VPS)
Installed all the files from git on server.

Kubernetes version:

_Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}_

Installed with Kubespray:
Helm chart version:

_Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}_

Other related technology + version:

How did you install Wire?

I followed these steps: https://docs.wire.com/how-to/install/kubernetes.html

And connecting to the server with iOS version on Xcode.


Question:

I followed all the steps from the manual, but I still got pods on pending. I also followed the steps on DNS and configured that the right way in my opinion. Can I get some assist please setting this demo up the right way?

Kind regards

**Comment by smoesai** [comment]
And when I run this command:

helm upgrade --install wire-server wire/wire-server -f values.yaml -f secrets.yaml --wait

I get this error:

Error: UPGRADE FAILED: "wire-server" has no deployed releases

**Comment by smoesai** [comment]
![Screenshot 2020-06-24 at 23 43 18](https://user-images.githubusercontent.com/29788467/85630764-8dd17f00-b674-11ea-8cac-7cc011202dc4.png)
I get this error in screenshot when running helm list --all

**Comment by lucendio** [comment]
Hi @smoesai,

> So, there are a couple of things, that come to mind:
>
> * you have a couple of pending pods. this is usually a sign or either K8s is not able to pull container images or not enough
> * resource being available so that the kube-scheduler can actually schedule the workload.
    register usually means email, even though the demo-smtp is running, you might need to do some DNS magic

My comments are still applicable.

Furthermore,

> I get this error in screenshot when running helm list --all

Either, it hints towards a mismatch between Helm v2 vs Helm v3 - meaning, first invocation of `install/upgrade` done with Helm v2, and the second with Helm v3. Or, you just missed defining `--namespace` in `helm list`.

**Comment by smoesai** [comment]
Hi lucendio,

So I found out what my problem was. I was running a VPS with 4 cores. That was the reason why

helm upgrade --install wire-server wire/wire-server -f values.yaml -f secrets.yaml --wait

wouldn't work.

I still can't register with email on an iOS device. same issue and same logs.

I still have on pod that is on pending:

kube-system   coredns-56bc6b976d-gzcth                                   0/1     Pending

And I looked at /activate/send in the logs above from my xcode debugging. And when I go to 

https://prod-nginz-https.wire.com/activate/send

it gives a respond. and when I go to the same page but with my domain, it gives a 404 not found error. Is the coredns pod causing this? And how to solve this error?

Thank you for your help.

Kind regards,

**Comment by smoesai** [comment]
Name:               coredns-56bc6b976d-gzcth
Namespace:          kube-system
Priority:           2000000000
PriorityClassName:  system-cluster-critical
Node:               <none>
Labels:             k8s-app=kube-dns
                    pod-template-hash=56bc6b976d
Annotations:        seccomp.security.alpha.kubernetes.io/pod: docker/default
Status:             Pending
IP:                 
Controlled By:      ReplicaSet/coredns-56bc6b976d
Containers:
  coredns:
    Image:       docker.io/coredns/coredns:1.5.0
    Ports:       53/UDP, 53/TCP, 9153/TCP
    Host Ports:  0/UDP, 0/TCP, 0/TCP
    Args:
      -conf
      /etc/coredns/Corefile
    Limits:
      memory:  170Mi
    Requests:
      cpu:        100m
      memory:     70Mi
    Liveness:     http-get http://:8080/health delay=0s timeout=5s period=10s #success=1 #failure=10
    Readiness:    http-get http://:8080/health delay=0s timeout=5s period=10s #success=1 #failure=10
    Environment:  <none>
    Mounts:
      /etc/coredns from config-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from coredns-token-rmg9x (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      coredns
    Optional:  false
  coredns-token-rmg9x:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  coredns-token-rmg9x
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     CriticalAddonsOnly
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  36s (x54 over 75m)  default-scheduler  0/1 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't satisfy existing pods anti-affinity rules.

**Comment by smoesai** [comment]
root@kubenode01:~# kubectl get pods --all-namespaces
NAMESPACE     NAME                                    READY   STATUS      RESTARTS   AGE
default       brig-index-migrate-data-csjzr           0/1     Completed   0          159m
default       cassandra-migrations-qzj75              0/1     Completed   0          161m
default       elasticsearch-index-create-psl88        0/1     Completed   0          160m
default       galley-migrate-data-wnfl6               0/1     Completed   0          159m
kube-system   coredns-56bc6b976d-xqhbv                1/1     Running     0          4m3s
kube-system   coredns-56bc6b976d-zx4zm                0/1     Pending     0          4m3s
kube-system   dns-autoscaler-56c969bdb8-kn2bl         1/1     Running     0          4m3s
kube-system   kube-apiserver-kubenode01               1/1     Running     0          3m59s
kube-system   kube-controller-manager-kubenode01      1/1     Running     0          3m57s
kube-system   kube-flannel-jhr9k                      2/2     Running     1          4m3s
kube-system   kube-proxy-5xpww                        1/1     Running     0          3m51s
kube-system   kube-scheduler-kubenode01               1/1     Running     0          4m
kube-system   kubernetes-dashboard-6c7466966c-przmr   1/1     Running     0          4m3s
kube-system   nodelocaldns-gllpw                      1/1     Running     0          4m3s
kube-system   tiller-deploy-8458f6c667-6qsk5          1/1     Running     0          4m3s
kube-system   weave-net-vcjn6                         2/2     Running     0          4m3s
root@kubenode01:~# kubectl logs coredns-56bc6b976d-zx4zm -n kube-system
root@kubenode01:~# kubectl logs coredns-56bc6b976d-xqhbv -n kube-system
E0626 02:45:11.899371       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Endpoints: Unauthorized
E0626 02:45:12.900153       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Service: Unauthorized
E0626 02:45:12.900721       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Namespace: Unauthorized
E0626 02:45:12.901824       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Endpoints: Unauthorized
.:53
2020-06-26T02:45:13.873Z [INFO] plugin/reload: Running configuration MD5 = 57c6391db370da399fc435576697eb7a
2020-06-26T02:45:13.874Z [INFO] CoreDNS-1.5.0
2020-06-26T02:45:13.874Z [INFO] linux/amd64, go1.12.2, e3f9a80
CoreDNS-1.5.0
linux/amd64, go1.12.2, e3f9a80
E0626 02:45:13.902291       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Service: Unauthorized
E0626 02:45:13.902962       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Namespace: Unauthorized
E0626 02:45:13.903898       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Endpoints: Unauthorized
E0626 02:45:14.904494       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Service: Unauthorized
E0626 02:45:14.904982       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Namespace: Unauthorized
E0626 02:45:14.905928       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Endpoints: Unauthorized
E0626 02:45:15.906589       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Service: Unauthorized
E0626 02:45:15.907239       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Namespace: Unauthorized
E0626 02:45:15.907955       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Endpoints: Unauthorized
E0626 02:45:16.908647       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Service: Unauthorized
E0626 02:45:16.909256       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Namespace: Unauthorized
E0626 02:45:16.910391       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Endpoints: Unauthorized
E0626 02:45:17.911685       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Service: Unauthorized
E0626 02:45:17.912681       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Namespace: Unauthorized
E0626 02:45:17.913628       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Endpoints: Unauthorized
E0626 02:45:18.913811       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Service: Unauthorized
E0626 02:45:18.914642       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Namespace: Unauthorized
E0626 02:45:18.915619       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Endpoints: Unauthorized
E0626 02:45:19.915503       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Service: Unauthorized
E0626 02:45:19.916526       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Namespace: Unauthorized
E0626 02:45:19.917343       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Endpoints: Unauthorized
E0626 02:45:20.917911       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Service: Unauthorized
E0626 02:45:20.918722       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Namespace: Unauthorized
E0626 02:45:20.920593       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Endpoints: Unauthorized
E0626 02:45:21.919681       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Service: Unauthorized
E0626 02:45:21.920580       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Namespace: Unauthorized
E0626 02:45:21.921801       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Endpoints: Unauthorized
2020-06-26T02:45:22.437Z [ERROR] plugin/errors: 2 6077897703429074925.653393467593635034.ip6.arpa. HINFO: dial tcp 213.136.95.11:53: connect: connection refused
2020-06-26T02:45:22.744Z [ERROR] plugin/errors: 2 6679783261083301734.8940001544453108429.in-addr.arpa. HINFO: dial tcp 213.136.95.10:53: i/o timeout

**Comment by lucendio** [comment]
Hi,

The pending coredns pod is fine, since you are in a single node installation. Is `webapp.doamin.tld` accessible from the browser?

> root@kubenode01: kubectl get pods --all-namespaces

You are missing a tone of pods in the list, that should be the result of all the Helm deployments mentioned in our documentation.

**Comment by smoesai** [comment]
This was a vps problem. I used 4 cores instead of 8.
