### ISSUE TITLE
Question: Where Can I check the logs for push notifications

### ISSUE THREAD

**Issue by ramesh8830** [wireapp/wire-server-deploy#302]
### Basic information

* On-premises: `yes`
* Cloud-Provider: `none`
* Installation type: `production`
* Kubernetes version: 
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
* Installed with Kubespray: `yes `
* Helm chart version: 
```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

* Other related technology + version: 

### How did you install Wire?

 Installed using instructions provided on the docs.wire.com and using ubuntu 18.04.4 LTS (Bionic Beaver). Using TLS wildcard certificate

### Question

where do i check the push notifications logs? I don't see any logs for push notifications inside gundeck pods. I am having hard time configuring ios push notifications.

Please advise.

**Comment by rahulit1991** [comment]
@ramesh8830, for this issue I am able to send push notification and able to see logs in gundeck. but in IOS 13 or later, the application crashed with push notification. Android push notification works perfectly.

**Comment by ramesh8830** [comment]
Hi @rahulit1991 

Android Notifications are works fine but IOS notifications are not working properly. Sometimes ios notifications are working with delay around 30min and sometimes not working at all.

I can't able to any logs in gundeck pods for both Android and IOS to see what's wrong.

**Comment by rahulit1991** [comment]
my colleague is working on IOS App. and same we facing an issue with push notification on IOS 13 or later. please check this GitHub issue. https://github.com/wireapp/wire-ios/issues/4447
