### ISSUE TITLE
Bug: Cassandra migrations getting failed

### ISSUE THREAD

**Issue by ramesh8830** [wireapp/wire-server-deploy#303]
### Basic information

* On-premises: `yes`
* Cloud-Provider: `none`
* Installation type: `production`
* Kubernetes version: 
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
* Installed with Kubespray: `yes `
* Helm chart version: 
```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

* Other related technology + version: 

### How to reproduce the issue?

```
root@kubenode03:~kubectl logs -n production cassandra-migrations-7zx2q -c gundeck-schema
Config file at /etc/wire/gundeck/conf/gundeck-schema.yaml does not exist, falling back to command-line arguments.

gundeck-schema: Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [AI_ADDRCONFIG], addrFamily = AF_UNSPEC, addrSocketType = Stream, addrProtocol = 0, addrAddress = <assumed to be undefined>, addrCanonName = <assumed to be undefined>}, host name: Just "cassandra-external", service name: Just "9042"): does not exist (Try again)
```

Please help me resolve this.

**Comment by ramesh8830** [comment]
Hi @lucendio @akshaymankar 

Can you please help me resolve this? I am struck at this and can't make progress.

**Comment by ramesh8830** [comment]
Can anyone help me resolve this error? All was working before and when I tried to redeploy everything then I struck here

**Comment by akshaymankar** [comment]
- Did you install the cassandra-external helm chart? If not, please do that.
- otherwise, do you see an `endpoint` called cassandra-external in your namespace? If not, please try to reinstall the cassandra-external helm chart and monitor if something is deleting the endpoint.
- otherwise, can you resolve `cassandra-external` from any pod in your namespace? If not, something is wrong with your `kube-dns`, please check that.
- otherwise, please try to figure out what is special about this pod that it is not able to resolve `cassandra-external`.

**Comment by ramesh8830** [comment]
Thank you @akshaymankar . Looks like something I messed up with dns while configuring Metallb load balancer by changing type from [NodePort to LoadBalancer](https://github.com/wireapp/wire-server-deploy/blob/develop/charts/nginx-ingress-controller/values.yaml#L80).

**Comment by iBinh** [comment]
I have following error
```
D, Connecting to x.x.x.x:9042
I, Known hosts: [se1:rack1:172.29.0.4:9042,se1:rack1:x.x.x.x:9042]
I, New control connection: se1:rack1:x.x.x.x:9042#<socket: 11>
D, Connection established: se1:rack1:x.x.x.x:9042#<socket: 12>
I, New migrations found.
I, [1] Initial schema
gundeck-schema: ResponseError {reHost = se1:rack1:x.x.x.x:9042, reTrace = Nothing, reWarn = [], reCause = Unavailable {unavailMessage = "Cannot achieve consistency level ALL", unavailConsistency = All, unavailNumRequired = 4, unavailNumAlive = 2}}
```

**Comment by julialongtin** [comment]
Check your ntp is running, and all nodes are showing the same time.
