### ISSUE TITLE
Bump image versions in charts to latest

### ISSUE THREAD

**Issue by ChrisPenner** [wireapp/wire-server-deploy#33]
- [x] Edit concourse (kubernetes_dev) pipeline to bump image versions inside wire-server-deploy on successful integration tests; this will cause a chart version bump with the new latest-greatest-images. 
- [x] This means we can remove the docker image overrides within Cailleach entirely and rely on the chart's values. This is better because we know everything works in the default charts (it passed CI); and it means that Cailleach uses the same image versions that an open source user would have.

- [x] Bump wire-server-deploy patch on merge to develop on wire-server
- [x] Bump wire-server-deploy patch on merge to master on wire-server-deploy
- [x] Bump wire-server-deploy minor on merge to master on wire-server

**Comment by jschaul** [comment]
I suppose this issue can be closed?
