### ISSUE TITLE
iOS push notifications not working

### ISSUE THREAD

**Issue by smoesai** [wireapp/wire-server-deploy#340]
### Basic information

* On-premises: 
Yes
* Cloud-Provider: 
Real AWS for SQS/SNS (push notifications) but not working.
* Installation type: 
Production
* Kubernetes version: 
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
* Helm version: 
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
* Installed with Kubespray:  
No
* (Helm) Charts version: 
* List of installed top-level charts:  
* Other related technologies + version: 

### How did you install Wire?

Installed on Ubuntu 18.04 following every step from docs.wire.com.
Installed Comodo certificate in Nginx-ingress.

### Question

Hi,

Is there anyone who has setup their own wire server and got the push notifications working on an iOS device?

If so, please help me..

I got everything working, only no push notifications when app is in background.

Thanks,
Shaif

**Comment by lucendio** [comment]
Please have a look at [Enable push notifications using the public appstore / playstore mobile Wire clients](https://docs.wire.com/how-to/install/configuration-options.html#enable-push-notifications-using-the-public-appstore-playstore-mobile-wire-clients).
