### ISSUE TITLE
Bug: video and audio calls are not working on the both mobile apps (android & ios)

### ISSUE THREAD

**Issue by ramesh8830** [wireapp/wire-server-deploy#366]
### Basic information

* On-premises: yes
* Cloud-Provider: no
* Installation type:  production 
* Kubernetes version: 
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
* Helm version: 
```
Client: &version.Version{SemVer:"v2.16.12", GitCommit:"47f0b88409e71fd9ca272abc7cd762a56a1c613e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.12", GitCommit:"47f0b88409e71fd9ca272abc7cd762a56a1c613e", GitTreeState:"clean"}
```

* Installed with Kubespray: yes  
* (Helm) Charts version: wire-server-0.122.0
* List of installed top-level charts: 
```
databases-ephemeral-0.122.0
cassandra-external-0.122.0
elasticsearch-external-0.122.0
wire-server-0.122.0
metallb-0.122.0
nginx-ingress-controller-0.122.0
nginx-ingress-services-0.122.0
```

Can't able to video or audio calls from the mobile apps (android & ios), not even able to get the video or audio calling icons working. webapp audio and videos calls are works fine. This happens during the recent upgrade to wire server deploy release.

**Comment by lucendio** [comment]
>  This happens during the recent upgrade to wire server deploy release.

Can you elaborate on this? What version did you upgrade from and which one did you upgrade to? How did you upgrade?

Also, did it work before? Did you upgrade the mobile clients, too?
