### ISSUE TITLE
Question: How to enable the Teams Settings ?

### ISSUE THREAD

**Issue by andriansandi** [wireapp/wire-server-deploy#451]
### Basic information
* On-premises: yes

### How did you install Wire?
Installing on our private servers (On-Premises)

### Question
Just wondering, how to enable the settings using on-premise? I have enabled it on the helm chart for the wire-server but got an error on the .secrets

Thanks for your help

**Comment by lucendio** [comment]
Hey @andriansandi,

[Team-Settings is a proprietary feature](https://github.com/wireapp/wire-server/tree/develop/charts/team-settings) I'm afraid, and unfortunately, you have to [go through Sales](https://wire.com/en/contact/sales/) in order to get access to it.
