### ISSUE TITLE
Question: The connection to the server localhost:8080 was refused

### ISSUE THREAD

**Issue by medbf321** [wireapp/wire-server-deploy#482]
### Basic information

* On-premises: yes
* Cloud-Provider: 
* Installation type: demo 
* Kubernetes version: 
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

* Helm version: 
`version.BuildInfo{Version:"v3.5.2", GitCommit:"", GitTreeState:"", GoVersion:"go1.16"}`

* Installed with Kubespray:  
* (Helm) Charts version: 
* List of installed top-level charts:  
* Other related technologies + version: 
* OS : Ubuntu 18.04

### How did you install Wire?
I followed the official doc for demo plan.
i installed nix and direnv dependencies.
I don't have any proxy or firewall.

### Question
The script executed without error, but when I do 'kubectl version' i have just client version and for the server 'connection refused'.

`Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}`

`The connection to the server localhost:8080 was refused - did you specify the right host or port?`

**Comment by arthurwolf** [comment]
Where exactly along the documentation's instructions are you when you run the "kubectl version" command?
