### ISSUE TITLE
sunset data to prevent PR#43 from filling up a node.

### ISSUE THREAD

**Issue by julialongtin** [wireapp/wire-server-deploy#50]
pull request #43 instantiated an elasticsearch database that will fill up in a few months. find some way to deal with this, so we can deploy this into a production(ish) environment.

**Comment by julialongtin** [comment]
It appears that the elasticsearch pod in the demo namespace was re-initialized yesterday.

**Comment by julialongtin** [comment]
It looks like there is a helm chart for the "Elasticsearch Curator", which was developed for this task. It sets up [Elasticsearch Curator](https://github.com/elastic/curator).

**Comment by tiago-loureiro** [comment]
Yes - I forgot to mention that, sorry. This is how we currently manage our clusters, i.e., we have 1 index per day and then delete indexes that are older than 3 days using a cron job

https://github.com/zinfra/hegemony/blob/00e52f974569ee14ba21c014194cb6f7ea2bc1e2/elasticsearch_kibana.yml#L55-L106

**Comment by julialongtin** [comment]
I'll go ahead and configure the elasticsearch curator similarly, then.

**Comment by julialongtin** [comment]
attempted to solve with:

https://github.com/wireapp/wire-server-deploy/pull/111

**Comment by julialongtin** [comment]
solution merged; closing issue.
