### ISSUE TITLE
Document for production on-premise (self-hosted) installation?

### ISSUE THREAD

**Issue by thanglvan** [wireapp/wire-server-deploy#6]
Hello,

Could you provide document for self-hosted installation?

Best regards.

**Comment by jschaul** [comment]
What are you missing outside of what is provided in the [README](https://github.com/wireapp/wire-server-deploy/blob/master/README.md) and [this file](https://github.com/wireapp/wire-server-deploy/blob/master/docs/configuration.md)?

**Comment by ajones747** [comment]
Who can we get to install this on ready made and provisioned servers?

**Comment by ajones747** [comment]
I have tried to contact them 2 separate times - no one has contacted me back. Can you please notify them to contact me please?

**Comment by jschaul** [comment]
> I have tried to contact them 2 separate times - no one has contacted me back. Can you please notify them to contact me please?

I asked the sales people - they cannot see any request that could be from you given the limited information (usernames "ajones747" and "thanglvan"). What name/email/company did you use when contacting the sales team? Otherwise, try sending an email directly to sales@wire.com

**Comment by ajones747** [comment]
I think my email is possibly blocked.  Can you ask them to contact me at AJ@hireapro.org or call me at 805-890-5852 please? I am not sure who that other username is. Thank you!

**Comment by fisx** [comment]
@thanglvan if you have specific questions that are not explained in the existing documentation, please open another issue and ask.

@ajones747 you should have been contacted justin a day or two ago.  please get in touch again if the connection still doesn't work.
