### ISSUE TITLE
udp listen external_ip:80: Permission denied

### ISSUE THREAD

**Issue by ramesh8830** [wireapp/wire-server-deploy#628]
In a production environment, restund services are failed to start.

```
root@restund:~# docker logs 73dc1ed9ddca
udp listen external_ip:80: Permission denied
root@restund:~# service restund status
● restund.service - restund
   Loaded: loaded (/etc/systemd/system/restund.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2023-06-29 10:56:11 PDT; 3min 32s ago
 Main PID: 25326 (code=exited, status=13)

Jun 29 10:56:10 restund docker[25326]: 6b60fc29f8bc: Pull complete
Jun 29 10:56:10 restund docker[25326]: 15a9a3320ca3: Pull complete
Jun 29 10:56:10 restund docker[25326]: 62f2df17690f: Pull complete
Jun 29 10:56:10 restund docker[25326]: 674b1606afa0: Pull complete
Jun 29 10:56:10 restund docker[25326]: 71debe1ef570: Pull complete
Jun 29 10:56:10 restund docker[25326]: Digest: sha256:2c5d390b2e64ff93e5950d621e6169e30886a4813d4b78b8821eb3602db231d1
Jun 29 10:56:10 restund docker[25326]: Status: Downloaded newer image for quay.io/wire/restund:v0.4.16b1.0.53
Jun 29 10:56:11 restund docker[25326]: udp listen external_ip:80: Permission denied
Jun 29 10:56:11 restund systemd[1]: restund.service: Main process exited, code=exited, status=13/n/a
Jun 29 10:56:11 restund systemd[1]: restund.service: Failed with result 'exit-code'.
root@restund:~#
```
Please help me

**Comment by ramesh8830** [comment]
Finally figured out how to fix this issue. 

1. have to change the file location of [restund.pem](https://github.com/wireapp/ansible-restund/blob/2b13967fee14cff1117af53e22d24d9b9adaad67/templates/restund.conf.j2#L10) to  /etc/restund/restund.pem. Otherwise restund.pem can't be read from /usr/local/etc/restund/restund.pem because under the [tasks](https://github.com/wireapp/ansible-restund/blob/2b13967fee14cff1117af53e22d24d9b9adaad67/tasks/restund.yml#L35) file location set to be stored at /etc/restund/restund.pem
2.  [restund_uid: 997](https://github.com/wireapp/ansible-restund/blob/2b13967fee14cff1117af53e22d24d9b9adaad67/defaults/main.yml#L7) has to changed to 0. If you want exposed restund at port 80 or 443. otherwise we have to exposed restund at different port as mentioned somewhere else in the document https://docs.wire.com/how-to/administrate/restund.html#static-list

**Comment by ramesh8830** [comment]
are the turn servers supposed work only on port 80 and 443?

**Comment by julialongtin** [comment]
We typically stick them there, so their packets get past bad firewalls.
