### ISSUE TITLE
Question: Help with deploying On-premise

### ISSUE THREAD

**Issue by VaultSoldier** [wireapp/wire-server-deploy#720]
### Basic information

* On-premises:  yes
* Cloud-Provider: none
* Installation type: production

### Question
Is there an option to deploy a wire server inside a docker container or on a host?
 
I tried compiling the source code with nix, but after compiling, I couldn't find dist/run-services and couldn't guess how to start the compiled services.

I also tried deploying to kubernetes using ansible, but there were syntax errors (not in the config files) during the kubernetes deployment phase.

I don't really want or need 99.9% SLA, so a docker, host, or single node kubernetes installation is preferred.

**Comment by supersven** [comment]
Hey @VaultSoldier :wave: 

Kubernetes is the only supported way to install Wire. Other installation methods in `wire-server` may be lacking the `webapp` or only provide ephemeral (non-persistent) datastores.
